package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.AcessoUsuarioFilial;
import br.inf.orion.eSafe.model.client.example.TbAcessoUsuarioFilialExample;
import br.inf.orion.eSafe.service.provider.client.AcessoUsuarioFilialSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AcessoUsuarioFilialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "countByExample")
	long countByExample(TbAcessoUsuarioFilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbAcessoUsuarioFilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_acesso_usuario_filial", "where id_usuario = #{idUsuario,jdbcType=INTEGER}",
			"and id_filial = #{idFilial,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(AcessoUsuarioFilial key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_acesso_usuario_filial (id_usuario, id_filial)",
			"values (#{idUsuario,jdbcType=INTEGER}, #{idFilial,jdbcType=INTEGER})" })
	int insert(AcessoUsuarioFilial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "insertSelective")
	int insertSelective(AcessoUsuarioFilial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_usuario", property = "idUsuario", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_filial", property = "idFilial", jdbcType = JdbcType.INTEGER, id = true) })
	List<AcessoUsuarioFilial> selectByExample(TbAcessoUsuarioFilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") AcessoUsuarioFilial record,
			@Param("example") TbAcessoUsuarioFilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioFilialSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") AcessoUsuarioFilial record,
			@Param("example") TbAcessoUsuarioFilialExample example);
}