package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.AcessoUsuarioTerminal;
import br.inf.orion.eSafe.model.client.example.TbAcessoUsuarioTerminalExample;
import br.inf.orion.eSafe.service.provider.client.AcessoUsuarioTerminalSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AcessoUsuarioTerminalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "countByExample")
	long countByExample(TbAcessoUsuarioTerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbAcessoUsuarioTerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_acesso_usuario_terminal", "where id_usuario = #{idUsuario,jdbcType=INTEGER}",
			"and id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(AcessoUsuarioTerminal key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_acesso_usuario_terminal (id_usuario, id_terminal)",
			"values (#{idUsuario,jdbcType=INTEGER}, #{idTerminal,jdbcType=INTEGER})" })
	int insert(AcessoUsuarioTerminal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "insertSelective")
	int insertSelective(AcessoUsuarioTerminal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_usuario", property = "idUsuario", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true) })
	List<AcessoUsuarioTerminal> selectByExample(TbAcessoUsuarioTerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") AcessoUsuarioTerminal record,
			@Param("example") TbAcessoUsuarioTerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioTerminalSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") AcessoUsuarioTerminal record,
			@Param("example") TbAcessoUsuarioTerminalExample example);
}