package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.ContatoFornecedor;
import br.inf.orion.eSafe.model.client.example.TbContatoFornecedorExample;
import br.inf.orion.eSafe.service.dao.client.TbContatoFornecedorSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContatoFornecedorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbContatoFornecedorSqlProvider.class, method = "countByExample")
	long countByExample(TbContatoFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = TbContatoFornecedorSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbContatoFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_contato_fornecedor", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_contato_fornecedor (id_contato, id_tipo_contato, ", "ds_contato, ds_observacao, ",
			"id_fornecedor)", "values (#{idContato,jdbcType=INTEGER}, #{idTipoContato,jdbcType=INTEGER}, ",
			"#{dsContato,jdbcType=VARCHAR}, #{dsObservacao,jdbcType=VARCHAR}, ", "#{idFornecedor,jdbcType=INTEGER})" })
	int insert(ContatoFornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = TbContatoFornecedorSqlProvider.class, method = "insertSelective")
	int insertSelective(ContatoFornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbContatoFornecedorSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER) })
	List<ContatoFornecedor> selectByExample(TbContatoFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_contato, id_tipo_contato, ds_contato, ds_observacao, id_fornecedor",
			"from public.tb_contato_fornecedor", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER) })
	ContatoFornecedor selectByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbContatoFornecedorSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ContatoFornecedor record,
			@Param("example") TbContatoFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbContatoFornecedorSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ContatoFornecedor record,
			@Param("example") TbContatoFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbContatoFornecedorSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ContatoFornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_contato_fornecedor", "set id_tipo_contato = #{idTipoContato,jdbcType=INTEGER},",
			"ds_contato = #{dsContato,jdbcType=VARCHAR},", "ds_observacao = #{dsObservacao,jdbcType=VARCHAR},",
			"id_fornecedor = #{idFornecedor,jdbcType=INTEGER}", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	int updateByPrimaryKey(ContatoFornecedor record);
}