package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.ContatoEstabelecimento;
import br.inf.orion.eSafe.model.client.example.TbContatoEstabelecimentoExample;
import br.inf.orion.eSafe.service.provider.client.ContatoEstabelecimentoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContatoEstabelecimentoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "countByExample")
	long countByExample(TbContatoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbContatoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_contato_estabelecimento", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_contato_estabelecimento (id_contato, id_tipo_contato, ",
			"ds_contato, ds_observacao, ", "id_estabelecimento)",
			"values (#{idContato,jdbcType=INTEGER}, #{idTipoContato,jdbcType=INTEGER}, ",
			"#{dsContato,jdbcType=VARCHAR}, #{dsObservacao,jdbcType=VARCHAR}, ",
			"#{idEstabelecimento,jdbcType=INTEGER})" })
	int insert(ContatoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "insertSelective")
	int insertSelective(ContatoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER) })
	List<ContatoEstabelecimento> selectByExample(TbContatoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_contato, id_tipo_contato, ds_contato, ds_observacao, id_estabelecimento",
			"from public.tb_contato_estabelecimento", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER) })
	ContatoEstabelecimento selectByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ContatoEstabelecimento record,
			@Param("example") TbContatoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ContatoEstabelecimento record,
			@Param("example") TbContatoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoEstabelecimentoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ContatoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_contato_estabelecimento", "set id_tipo_contato = #{idTipoContato,jdbcType=INTEGER},",
			"ds_contato = #{dsContato,jdbcType=VARCHAR},", "ds_observacao = #{dsObservacao,jdbcType=VARCHAR},",
			"id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}",
			"where id_contato = #{idContato,jdbcType=INTEGER}" })
	int updateByPrimaryKey(ContatoEstabelecimento record);
}