package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.ContatoFabricante;
import br.inf.orion.eSafe.model.client.example.TbContatoFabricanteExample;
import br.inf.orion.eSafe.service.provider.client.ContatoFabricanteSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ContatoFabricanteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = ContatoFabricanteSqlProvider.class, method = "countByExample")
	long countByExample(TbContatoFabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = ContatoFabricanteSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbContatoFabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_contato_fabricante", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_contato_fabricante (id_contato, id_tipo_contato, ", "ds_contato, ds_observacao, ",
			"id_fabricante)", "values (#{idContato,jdbcType=INTEGER}, #{idTipoContato,jdbcType=INTEGER}, ",
			"#{dsContato,jdbcType=VARCHAR}, #{dsObservacao,jdbcType=VARCHAR}, ", "#{idFabricante,jdbcType=INTEGER})" })
	int insert(ContatoFabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = ContatoFabricanteSqlProvider.class, method = "insertSelective")
	int insertSelective(ContatoFabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = ContatoFabricanteSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_fabricante", property = "idFabricante", jdbcType = JdbcType.INTEGER) })
	List<ContatoFabricante> selectByExample(TbContatoFabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_contato, id_tipo_contato, ds_contato, ds_observacao, id_fabricante",
			"from public.tb_contato_fabricante", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_contato", property = "idContato", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_tipo_contato", property = "idTipoContato", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_contato", property = "dsContato", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_observacao", property = "dsObservacao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_fabricante", property = "idFabricante", jdbcType = JdbcType.INTEGER) })
	ContatoFabricante selectByPrimaryKey(Integer idContato);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoFabricanteSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ContatoFabricante record,
			@Param("example") TbContatoFabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoFabricanteSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ContatoFabricante record,
			@Param("example") TbContatoFabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = ContatoFabricanteSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ContatoFabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_contato_fabricante", "set id_tipo_contato = #{idTipoContato,jdbcType=INTEGER},",
			"ds_contato = #{dsContato,jdbcType=VARCHAR},", "ds_observacao = #{dsObservacao,jdbcType=VARCHAR},",
			"id_fabricante = #{idFabricante,jdbcType=INTEGER}", "where id_contato = #{idContato,jdbcType=INTEGER}" })
	int updateByPrimaryKey(ContatoFabricante record);
}