package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.Dispositivo;
import br.inf.orion.eSafe.model.client.example.TbDispositivoExample;
import br.inf.orion.eSafe.service.dao.client.TbDispositivoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DispositivoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbDispositivoSqlProvider.class, method = "countByExample")
	long countByExample(TbDispositivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = TbDispositivoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbDispositivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_dispositivo", "where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idDispositivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_dispositivo (id_dispositivo, ds_dispositivo)",
			"values (#{idDispositivo,jdbcType=INTEGER}, #{dsDispositivo,jdbcType=VARCHAR})" })
	int insert(Dispositivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = TbDispositivoSqlProvider.class, method = "insertSelective")
	int insertSelective(Dispositivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbDispositivoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_dispositivo", property = "dsDispositivo", jdbcType = JdbcType.VARCHAR) })
	List<Dispositivo> selectByExample(TbDispositivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_dispositivo, ds_dispositivo", "from public.tb_dispositivo",
			"where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_dispositivo", property = "dsDispositivo", jdbcType = JdbcType.VARCHAR) })
	Dispositivo selectByPrimaryKey(Integer idDispositivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbDispositivoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Dispositivo record, @Param("example") TbDispositivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbDispositivoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Dispositivo record, @Param("example") TbDispositivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbDispositivoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Dispositivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_dispositivo", "set ds_dispositivo = #{dsDispositivo,jdbcType=VARCHAR}",
			"where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Dispositivo record);
}