package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.DispositivoModeloKey;
import br.inf.orion.eSafe.model.client.example.TbDispositivoModeloExample;
import br.inf.orion.eSafe.service.dao.client.TbDispositivoModeloSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DispositivoModeloMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbDispositivoModeloSqlProvider.class, method = "countByExample")
	long countByExample(TbDispositivoModeloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = TbDispositivoModeloSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbDispositivoModeloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_dispositivo_modelo", "where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}",
			"and id_modelo = #{idModelo,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(DispositivoModeloKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_dispositivo_modelo (id_dispositivo, id_modelo)",
			"values (#{idDispositivo,jdbcType=INTEGER}, #{idModelo,jdbcType=INTEGER})" })
	int insert(DispositivoModeloKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = TbDispositivoModeloSqlProvider.class, method = "insertSelective")
	int insertSelective(DispositivoModeloKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbDispositivoModeloSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_modelo", property = "idModelo", jdbcType = JdbcType.INTEGER, id = true) })
	List<DispositivoModeloKey> selectByExample(TbDispositivoModeloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbDispositivoModeloSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") DispositivoModeloKey record,
			@Param("example") TbDispositivoModeloExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_dispositivo_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbDispositivoModeloSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") DispositivoModeloKey record,
			@Param("example") TbDispositivoModeloExample example);
}