package br.inf.orion.eSafe.model.mapper.client;

import br.inf.orion.eSafe.model.client.Estabelecimento;
import br.inf.orion.eSafe.model.client.example.TbEstabelecimentoExample;
import br.inf.orion.eSafe.service.dao.client.TbEstabelecimentoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EstabelecimentoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbEstabelecimentoSqlProvider.class, method = "countByExample")
	long countByExample(TbEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = TbEstabelecimentoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_estabelecimento",
			"where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idEstabelecimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_estabelecimento (id_estabelecimento, id_filial, ",
			"id_fornecedor, ds_estabelecimento, ", "ic_ativo)",
			"values (#{idEstabelecimento,jdbcType=INTEGER}, #{idFilial,jdbcType=INTEGER}, ",
			"#{idFornecedor,jdbcType=INTEGER}, #{dsEstabelecimento,jdbcType=VARCHAR}, ", "#{icAtivo,jdbcType=BIT})" })
	int insert(Estabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = TbEstabelecimentoSqlProvider.class, method = "insertSelective")
	int insertSelective(Estabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = TbEstabelecimentoSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_filial", property = "idFilial", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_estabelecimento", property = "dsEstabelecimento", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	List<Estabelecimento> selectByExample(TbEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_estabelecimento, id_filial, id_fornecedor, ds_estabelecimento, ic_ativo",
			"from public.tb_estabelecimento", "where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_filial", property = "idFilial", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_estabelecimento", property = "dsEstabelecimento", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	Estabelecimento selectByPrimaryKey(Integer idEstabelecimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbEstabelecimentoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Estabelecimento record,
			@Param("example") TbEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbEstabelecimentoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Estabelecimento record, @Param("example") TbEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = TbEstabelecimentoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Estabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_estabelecimento", "set id_filial = #{idFilial,jdbcType=INTEGER},",
			"id_fornecedor = #{idFornecedor,jdbcType=INTEGER},",
			"ds_estabelecimento = #{dsEstabelecimento,jdbcType=VARCHAR},", "ic_ativo = #{icAtivo,jdbcType=BIT}",
			"where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Estabelecimento record);
}