package br.inf.orion.eSafe.service.provider.client;

import br.inf.orion.eSafe.model.client.StatusDispositivo;
import br.inf.orion.eSafe.model.client.example.TbStatusDispositivoExample;
import br.inf.orion.eSafe.model.client.example.TbStatusDispositivoExample.Criteria;
import br.inf.orion.eSafe.model.client.example.TbStatusDispositivoExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class StatusDispositivoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String countByExample(TbStatusDispositivoExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("public.tb_status_dispositivo");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String deleteByExample(TbStatusDispositivoExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("public.tb_status_dispositivo");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String insertSelective(StatusDispositivo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("public.tb_status_dispositivo");
		if (record.getIdDispositivo() != null) {
			sql.VALUES("id_dispositivo", "#{idDispositivo,jdbcType=INTEGER}");
		}
		if (record.getCdStatus() != null) {
			sql.VALUES("cd_status", "#{cdStatus,jdbcType=INTEGER}");
		}
		if (record.getDsStatus() != null) {
			sql.VALUES("ds_status", "#{dsStatus,jdbcType=VARCHAR}");
		}
		if (record.getIdSeveridade() != null) {
			sql.VALUES("id_severidade", "#{idSeveridade,jdbcType=INTEGER}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String selectByExample(TbStatusDispositivoExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id_dispositivo");
		} else {
			sql.SELECT("id_dispositivo");
		}
		sql.SELECT("cd_status");
		sql.SELECT("ds_status");
		sql.SELECT("id_severidade");
		sql.FROM("public.tb_status_dispositivo");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		StatusDispositivo record = (StatusDispositivo) parameter.get("record");
		TbStatusDispositivoExample example = (TbStatusDispositivoExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("public.tb_status_dispositivo");
		if (record.getIdDispositivo() != null) {
			sql.SET("id_dispositivo = #{record.idDispositivo,jdbcType=INTEGER}");
		}
		if (record.getCdStatus() != null) {
			sql.SET("cd_status = #{record.cdStatus,jdbcType=INTEGER}");
		}
		if (record.getDsStatus() != null) {
			sql.SET("ds_status = #{record.dsStatus,jdbcType=VARCHAR}");
		}
		if (record.getIdSeveridade() != null) {
			sql.SET("id_severidade = #{record.idSeveridade,jdbcType=INTEGER}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_status_dispositivo");
		sql.SET("id_dispositivo = #{record.idDispositivo,jdbcType=INTEGER}");
		sql.SET("cd_status = #{record.cdStatus,jdbcType=INTEGER}");
		sql.SET("ds_status = #{record.dsStatus,jdbcType=VARCHAR}");
		sql.SET("id_severidade = #{record.idSeveridade,jdbcType=INTEGER}");
		TbStatusDispositivoExample example = (TbStatusDispositivoExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByPrimaryKeySelective(StatusDispositivo record) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_status_dispositivo");
		if (record.getDsStatus() != null) {
			sql.SET("ds_status = #{dsStatus,jdbcType=VARCHAR}");
		}
		if (record.getIdSeveridade() != null) {
			sql.SET("id_severidade = #{idSeveridade,jdbcType=INTEGER}");
		}
		sql.WHERE("id_dispositivo = #{idDispositivo,jdbcType=INTEGER}");
		sql.WHERE("cd_status = #{cdStatus,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected void applyWhere(SQL sql, TbStatusDispositivoExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}