package br.inf.orion.eSafe.model;

public class FuncionalidadeClienteKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_funcionalidade_cliente.id_funcionalidade
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    private Integer idFuncionalidade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_funcionalidade_cliente.id_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    private Integer idCliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_funcionalidade_cliente.id_funcionalidade
     *
     * @return the value of public.tb_funcionalidade_cliente.id_funcionalidade
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public Integer getIdFuncionalidade() {
        return idFuncionalidade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_funcionalidade_cliente.id_funcionalidade
     *
     * @param idFuncionalidade the value for public.tb_funcionalidade_cliente.id_funcionalidade
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setIdFuncionalidade(Integer idFuncionalidade) {
        this.idFuncionalidade = idFuncionalidade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_funcionalidade_cliente.id_cliente
     *
     * @return the value of public.tb_funcionalidade_cliente.id_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_funcionalidade_cliente.id_cliente
     *
     * @param idCliente the value for public.tb_funcionalidade_cliente.id_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
}