package br.inf.orion.eSafe.model;

public class Terminal {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_terminal.id_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Integer idTerminal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_terminal.id_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Integer idCliente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_terminal.nr_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String nrTerminal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_terminal.id_terminal
	 * @return  the value of public.tb_terminal.id_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Integer getIdTerminal() {
		return idTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_terminal.id_terminal
	 * @param idTerminal  the value for public.tb_terminal.id_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setIdTerminal(Integer idTerminal) {
		this.idTerminal = idTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_terminal.id_cliente
	 * @return  the value of public.tb_terminal.id_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Integer getIdCliente() {
		return idCliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_terminal.id_cliente
	 * @param idCliente  the value for public.tb_terminal.id_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_terminal.nr_terminal
	 * @return  the value of public.tb_terminal.nr_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getNrTerminal() {
		return nrTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_terminal.nr_terminal
	 * @param nrTerminal  the value for public.tb_terminal.nr_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setNrTerminal(String nrTerminal) {
		this.nrTerminal = nrTerminal;
	}
}