package br.inf.orion.eSafe.model;

public class TipoEndereco {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_tipo_endereco.tp_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    private Integer tpEndereco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_tipo_endereco.ds_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    private String dsTipoEndereco;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_tipo_endereco.tp_endereco
     *
     * @return the value of public.tb_tipo_endereco.tp_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public Integer getTpEndereco() {
        return tpEndereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_tipo_endereco.tp_endereco
     *
     * @param tpEndereco the value for public.tb_tipo_endereco.tp_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setTpEndereco(Integer tpEndereco) {
        this.tpEndereco = tpEndereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_tipo_endereco.ds_tipo_endereco
     *
     * @return the value of public.tb_tipo_endereco.ds_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String getDsTipoEndereco() {
        return dsTipoEndereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_tipo_endereco.ds_tipo_endereco
     *
     * @param dsTipoEndereco the value for public.tb_tipo_endereco.ds_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setDsTipoEndereco(String dsTipoEndereco) {
        this.dsTipoEndereco = dsTipoEndereco;
    }
}