package br.inf.orion.eSafe.model;

import java.util.Date;

public class Usuario {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.id_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ds_login
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String dsLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ds_email
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String dsEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ds_senha
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String dsSenha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ds_nome_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String dsNomeUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.dt_criacao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Date dtCriacao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.dt_alteracao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Date dtAlteracao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ds_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private String dsToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.dt_gera_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Date dtGeraToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.id_perfil
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Integer idPerfil;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario.ic_ativo
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	private Boolean icAtivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.id_usuario
	 * @return  the value of public.tb_usuario.id_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.id_usuario
	 * @param idUsuario  the value for public.tb_usuario.id_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ds_login
	 * @return  the value of public.tb_usuario.ds_login
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getDsLogin() {
		return dsLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ds_login
	 * @param dsLogin  the value for public.tb_usuario.ds_login
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDsLogin(String dsLogin) {
		this.dsLogin = dsLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ds_email
	 * @return  the value of public.tb_usuario.ds_email
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getDsEmail() {
		return dsEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ds_email
	 * @param dsEmail  the value for public.tb_usuario.ds_email
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDsEmail(String dsEmail) {
		this.dsEmail = dsEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ds_senha
	 * @return  the value of public.tb_usuario.ds_senha
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getDsSenha() {
		return dsSenha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ds_senha
	 * @param dsSenha  the value for public.tb_usuario.ds_senha
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDsSenha(String dsSenha) {
		this.dsSenha = dsSenha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ds_nome_usuario
	 * @return  the value of public.tb_usuario.ds_nome_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getDsNomeUsuario() {
		return dsNomeUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ds_nome_usuario
	 * @param dsNomeUsuario  the value for public.tb_usuario.ds_nome_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDsNomeUsuario(String dsNomeUsuario) {
		this.dsNomeUsuario = dsNomeUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.dt_criacao
	 * @return  the value of public.tb_usuario.dt_criacao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Date getDtCriacao() {
		return dtCriacao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.dt_criacao
	 * @param dtCriacao  the value for public.tb_usuario.dt_criacao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDtCriacao(Date dtCriacao) {
		this.dtCriacao = dtCriacao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.dt_alteracao
	 * @return  the value of public.tb_usuario.dt_alteracao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Date getDtAlteracao() {
		return dtAlteracao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.dt_alteracao
	 * @param dtAlteracao  the value for public.tb_usuario.dt_alteracao
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDtAlteracao(Date dtAlteracao) {
		this.dtAlteracao = dtAlteracao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ds_token
	 * @return  the value of public.tb_usuario.ds_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getDsToken() {
		return dsToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ds_token
	 * @param dsToken  the value for public.tb_usuario.ds_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDsToken(String dsToken) {
		this.dsToken = dsToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.dt_gera_token
	 * @return  the value of public.tb_usuario.dt_gera_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Date getDtGeraToken() {
		return dtGeraToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.dt_gera_token
	 * @param dtGeraToken  the value for public.tb_usuario.dt_gera_token
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDtGeraToken(Date dtGeraToken) {
		this.dtGeraToken = dtGeraToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.id_perfil
	 * @return  the value of public.tb_usuario.id_perfil
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Integer getIdPerfil() {
		return idPerfil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.id_perfil
	 * @param idPerfil  the value for public.tb_usuario.id_perfil
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario.ic_ativo
	 * @return  the value of public.tb_usuario.ic_ativo
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Boolean getIcAtivo() {
		return icAtivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario.ic_ativo
	 * @param icAtivo  the value for public.tb_usuario.ic_ativo
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setIcAtivo(Boolean icAtivo) {
		this.icAtivo = icAtivo;
	}
}