package br.inf.orion.eSafe.client.model;

public class Dispositivo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_dispositivo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idDispositivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_dispositivo.ds_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsDispositivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_dispositivo.id_dispositivo
	 * @return  the value of public.tb_dispositivo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdDispositivo() {
		return idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_dispositivo.id_dispositivo
	 * @param idDispositivo  the value for public.tb_dispositivo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdDispositivo(Integer idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_dispositivo.ds_dispositivo
	 * @return  the value of public.tb_dispositivo.ds_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsDispositivo() {
		return dsDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_dispositivo.ds_dispositivo
	 * @param dsDispositivo  the value for public.tb_dispositivo.ds_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsDispositivo(String dsDispositivo) {
		this.dsDispositivo = dsDispositivo;
	}
}