package br.inf.orion.eSafe.client.model;

public class DispositivoModeloKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_dispositivo_modelo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idDispositivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_dispositivo_modelo.id_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idModelo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_dispositivo_modelo.id_dispositivo
	 * @return  the value of public.tb_dispositivo_modelo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdDispositivo() {
		return idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_dispositivo_modelo.id_dispositivo
	 * @param idDispositivo  the value for public.tb_dispositivo_modelo.id_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdDispositivo(Integer idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_dispositivo_modelo.id_modelo
	 * @return  the value of public.tb_dispositivo_modelo.id_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdModelo() {
		return idModelo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_dispositivo_modelo.id_modelo
	 * @param idModelo  the value for public.tb_dispositivo_modelo.id_modelo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}
}