package br.inf.orion.eSafe.client.model;

import java.util.Date;

public class Monitoracao {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_monitoracao.id_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idTerminal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_monitoracao.dt_envio
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Date dtEnvio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_monitoracao.ic_status_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer icStatusTerminal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_monitoracao.id_terminal
	 * @return  the value of public.tb_monitoracao.id_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdTerminal() {
		return idTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_monitoracao.id_terminal
	 * @param idTerminal  the value for public.tb_monitoracao.id_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdTerminal(Integer idTerminal) {
		this.idTerminal = idTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_monitoracao.dt_envio
	 * @return  the value of public.tb_monitoracao.dt_envio
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Date getDtEnvio() {
		return dtEnvio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_monitoracao.dt_envio
	 * @param dtEnvio  the value for public.tb_monitoracao.dt_envio
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDtEnvio(Date dtEnvio) {
		this.dtEnvio = dtEnvio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_monitoracao.ic_status_terminal
	 * @return  the value of public.tb_monitoracao.ic_status_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIcStatusTerminal() {
		return icStatusTerminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_monitoracao.ic_status_terminal
	 * @param icStatusTerminal  the value for public.tb_monitoracao.ic_status_terminal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIcStatusTerminal(Integer icStatusTerminal) {
		this.icStatusTerminal = icStatusTerminal;
	}
}