package br.inf.orion.eSafe.client.model;

public class Sensor extends SensorKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_sensor.ds_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	private String dsSensor;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_sensor.ds_sensor
	 * @return  the value of public.tb_sensor.ds_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public String getDsSensor() {
		return dsSensor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_sensor.ds_sensor
	 * @param dsSensor  the value for public.tb_sensor.ds_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public void setDsSensor(String dsSensor) {
		this.dsSensor = dsSensor;
	}
}