package br.inf.orion.eSafe.client.model;

import java.util.Date;

public class UsuarioExterno {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.id_usuario
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.ds_login
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.ds_nome
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.id_detalhe
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String idDetalhe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Boolean icAtivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_usuario_externo.dt_inclusao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Date dtInclusao;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.id_usuario
	 * @return  the value of public.tb_usuario_externo.id_usuario
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.id_usuario
	 * @param idUsuario  the value for public.tb_usuario_externo.id_usuario
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.ds_login
	 * @return  the value of public.tb_usuario_externo.ds_login
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsLogin() {
		return dsLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.ds_login
	 * @param dsLogin  the value for public.tb_usuario_externo.ds_login
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsLogin(String dsLogin) {
		this.dsLogin = dsLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.ds_nome
	 * @return  the value of public.tb_usuario_externo.ds_nome
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsNome() {
		return dsNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.ds_nome
	 * @param dsNome  the value for public.tb_usuario_externo.ds_nome
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsNome(String dsNome) {
		this.dsNome = dsNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.id_detalhe
	 * @return  the value of public.tb_usuario_externo.id_detalhe
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getIdDetalhe() {
		return idDetalhe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.id_detalhe
	 * @param idDetalhe  the value for public.tb_usuario_externo.id_detalhe
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdDetalhe(String idDetalhe) {
		this.idDetalhe = idDetalhe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.ic_ativo
	 * @return  the value of public.tb_usuario_externo.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Boolean getIcAtivo() {
		return icAtivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.ic_ativo
	 * @param icAtivo  the value for public.tb_usuario_externo.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIcAtivo(Boolean icAtivo) {
		this.icAtivo = icAtivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_usuario_externo.dt_inclusao
	 * @return  the value of public.tb_usuario_externo.dt_inclusao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Date getDtInclusao() {
		return dtInclusao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_usuario_externo.dt_inclusao
	 * @param dtInclusao  the value for public.tb_usuario_externo.dt_inclusao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDtInclusao(Date dtInclusao) {
		this.dtInclusao = dtInclusao;
	}
}