package br.inf.orion.eSafe.model.client;

public class EnderecoEstabelecimento extends EnderecoEstabelecimentoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.tp_endereco
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer tpEndereco;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_logradouro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsLogradouro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_complemento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsComplemento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_bairro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsBairro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_cidade
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsCidade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_estado
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsEstado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_endereco_estabelecimento.ds_codigo_postal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsCodigoPostal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.tp_endereco
	 * @return  the value of public.tb_endereco_estabelecimento.tp_endereco
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getTpEndereco() {
		return tpEndereco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.tp_endereco
	 * @param tpEndereco  the value for public.tb_endereco_estabelecimento.tp_endereco
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setTpEndereco(Integer tpEndereco) {
		this.tpEndereco = tpEndereco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_logradouro
	 * @return  the value of public.tb_endereco_estabelecimento.ds_logradouro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsLogradouro() {
		return dsLogradouro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_logradouro
	 * @param dsLogradouro  the value for public.tb_endereco_estabelecimento.ds_logradouro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsLogradouro(String dsLogradouro) {
		this.dsLogradouro = dsLogradouro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_complemento
	 * @return  the value of public.tb_endereco_estabelecimento.ds_complemento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsComplemento() {
		return dsComplemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_complemento
	 * @param dsComplemento  the value for public.tb_endereco_estabelecimento.ds_complemento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsComplemento(String dsComplemento) {
		this.dsComplemento = dsComplemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_bairro
	 * @return  the value of public.tb_endereco_estabelecimento.ds_bairro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsBairro() {
		return dsBairro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_bairro
	 * @param dsBairro  the value for public.tb_endereco_estabelecimento.ds_bairro
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsBairro(String dsBairro) {
		this.dsBairro = dsBairro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_cidade
	 * @return  the value of public.tb_endereco_estabelecimento.ds_cidade
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsCidade() {
		return dsCidade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_cidade
	 * @param dsCidade  the value for public.tb_endereco_estabelecimento.ds_cidade
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsCidade(String dsCidade) {
		this.dsCidade = dsCidade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_estado
	 * @return  the value of public.tb_endereco_estabelecimento.ds_estado
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsEstado() {
		return dsEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_estado
	 * @param dsEstado  the value for public.tb_endereco_estabelecimento.ds_estado
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsEstado(String dsEstado) {
		this.dsEstado = dsEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_endereco_estabelecimento.ds_codigo_postal
	 * @return  the value of public.tb_endereco_estabelecimento.ds_codigo_postal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsCodigoPostal() {
		return dsCodigoPostal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_endereco_estabelecimento.ds_codigo_postal
	 * @param dsCodigoPostal  the value for public.tb_endereco_estabelecimento.ds_codigo_postal
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsCodigoPostal(String dsCodigoPostal) {
		this.dsCodigoPostal = dsCodigoPostal;
	}
}