package br.inf.orion.eSafe.model.client;

public class Fabricante {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_fabricante.id_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Integer idFabricante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_fabricante.ds_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsFabricante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_fabricante.ds_cnpj
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private String dsCnpj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_fabricante.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	private Boolean icAtivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_fabricante.id_fabricante
	 * @return  the value of public.tb_fabricante.id_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Integer getIdFabricante() {
		return idFabricante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_fabricante.id_fabricante
	 * @param idFabricante  the value for public.tb_fabricante.id_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIdFabricante(Integer idFabricante) {
		this.idFabricante = idFabricante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_fabricante.ds_fabricante
	 * @return  the value of public.tb_fabricante.ds_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsFabricante() {
		return dsFabricante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_fabricante.ds_fabricante
	 * @param dsFabricante  the value for public.tb_fabricante.ds_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsFabricante(String dsFabricante) {
		this.dsFabricante = dsFabricante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_fabricante.ds_cnpj
	 * @return  the value of public.tb_fabricante.ds_cnpj
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getDsCnpj() {
		return dsCnpj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_fabricante.ds_cnpj
	 * @param dsCnpj  the value for public.tb_fabricante.ds_cnpj
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDsCnpj(String dsCnpj) {
		this.dsCnpj = dsCnpj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_fabricante.ic_ativo
	 * @return  the value of public.tb_fabricante.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Boolean getIcAtivo() {
		return icAtivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_fabricante.ic_ativo
	 * @param icAtivo  the value for public.tb_fabricante.ic_ativo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setIcAtivo(Boolean icAtivo) {
		this.icAtivo = icAtivo;
	}
}