package br.inf.orion.eSafe.client.service.provider;

import br.inf.orion.eSafe.client.model.ContatoFilial;
import br.inf.orion.eSafe.client.model.example.ContatoFilialExample;
import br.inf.orion.eSafe.client.model.example.ContatoFilialExample.Criteria;
import br.inf.orion.eSafe.client.model.example.ContatoFilialExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ContatoFilialSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String countByExample(ContatoFilialExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("public.tb_contato_filial");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String deleteByExample(ContatoFilialExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("public.tb_contato_filial");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String insertSelective(ContatoFilial record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("public.tb_contato_filial");
		if (record.getIdContato() != null) {
			sql.VALUES("id_contato", "#{idContato,jdbcType=INTEGER}");
		}
		if (record.getIdTipoContato() != null) {
			sql.VALUES("id_tipo_contato", "#{idTipoContato,jdbcType=INTEGER}");
		}
		if (record.getDsContato() != null) {
			sql.VALUES("ds_contato", "#{dsContato,jdbcType=VARCHAR}");
		}
		if (record.getDsObservacao() != null) {
			sql.VALUES("ds_observacao", "#{dsObservacao,jdbcType=VARCHAR}");
		}
		if (record.getIdFilial() != null) {
			sql.VALUES("id_filial", "#{idFilial,jdbcType=INTEGER}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String selectByExample(ContatoFilialExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id_contato");
		} else {
			sql.SELECT("id_contato");
		}
		sql.SELECT("id_tipo_contato");
		sql.SELECT("ds_contato");
		sql.SELECT("ds_observacao");
		sql.SELECT("id_filial");
		sql.FROM("public.tb_contato_filial");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		ContatoFilial record = (ContatoFilial) parameter.get("record");
		ContatoFilialExample example = (ContatoFilialExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("public.tb_contato_filial");
		if (record.getIdContato() != null) {
			sql.SET("id_contato = #{record.idContato,jdbcType=INTEGER}");
		}
		if (record.getIdTipoContato() != null) {
			sql.SET("id_tipo_contato = #{record.idTipoContato,jdbcType=INTEGER}");
		}
		if (record.getDsContato() != null) {
			sql.SET("ds_contato = #{record.dsContato,jdbcType=VARCHAR}");
		}
		if (record.getDsObservacao() != null) {
			sql.SET("ds_observacao = #{record.dsObservacao,jdbcType=VARCHAR}");
		}
		if (record.getIdFilial() != null) {
			sql.SET("id_filial = #{record.idFilial,jdbcType=INTEGER}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_contato_filial");
		sql.SET("id_contato = #{record.idContato,jdbcType=INTEGER}");
		sql.SET("id_tipo_contato = #{record.idTipoContato,jdbcType=INTEGER}");
		sql.SET("ds_contato = #{record.dsContato,jdbcType=VARCHAR}");
		sql.SET("ds_observacao = #{record.dsObservacao,jdbcType=VARCHAR}");
		sql.SET("id_filial = #{record.idFilial,jdbcType=INTEGER}");
		ContatoFilialExample example = (ContatoFilialExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByPrimaryKeySelective(ContatoFilial record) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_contato_filial");
		if (record.getIdTipoContato() != null) {
			sql.SET("id_tipo_contato = #{idTipoContato,jdbcType=INTEGER}");
		}
		if (record.getDsContato() != null) {
			sql.SET("ds_contato = #{dsContato,jdbcType=VARCHAR}");
		}
		if (record.getDsObservacao() != null) {
			sql.SET("ds_observacao = #{dsObservacao,jdbcType=VARCHAR}");
		}
		if (record.getIdFilial() != null) {
			sql.SET("id_filial = #{idFilial,jdbcType=INTEGER}");
		}
		sql.WHERE("id_contato = #{idContato,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_contato_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected void applyWhere(SQL sql, ContatoFilialExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}