package br.inf.orion.eSafe.client.service.provider;

import br.inf.orion.eSafe.client.model.Operacao;
import br.inf.orion.eSafe.client.model.example.OperacaoExample;
import br.inf.orion.eSafe.client.model.example.OperacaoExample.Criteria;
import br.inf.orion.eSafe.client.model.example.OperacaoExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OperacaoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String countByExample(OperacaoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("public.tb_operacao");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String deleteByExample(OperacaoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("public.tb_operacao");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String insertSelective(Operacao record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("public.tb_operacao");
        
        if (record.getIdOperacao() != null) {
            sql.VALUES("id_operacao", "#{idOperacao,jdbcType=OTHER}");
        }
        
        if (record.getDtOperacao() != null) {
            sql.VALUES("dt_operacao", "#{dtOperacao,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIdTerminal() != null) {
            sql.VALUES("id_terminal", "#{idTerminal,jdbcType=INTEGER}");
        }
        
        if (record.getIdUsuario() != null) {
            sql.VALUES("id_usuario", "#{idUsuario,jdbcType=INTEGER}");
        }
        
        if (record.getIdTransacao() != null) {
            sql.VALUES("id_transacao", "#{idTransacao,jdbcType=INTEGER}");
        }
        
        if (record.getVlOperacao() != null) {
            sql.VALUES("vl_operacao", "#{vlOperacao,jdbcType=DOUBLE}");
        }
        
        if (record.getCdMoeda() != null) {
            sql.VALUES("cd_moeda", "#{cdMoeda,jdbcType=INTEGER}");
        }
        
        if (record.getTpOperacao() != null) {
            sql.VALUES("tp_operacao", "#{tpOperacao,jdbcType=OTHER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String selectByExample(OperacaoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id_operacao");
        } else {
            sql.SELECT("id_operacao");
        }
        sql.SELECT("dt_operacao");
        sql.SELECT("id_terminal");
        sql.SELECT("id_usuario");
        sql.SELECT("id_transacao");
        sql.SELECT("vl_operacao");
        sql.SELECT("cd_moeda");
        sql.SELECT("tp_operacao");
        sql.FROM("public.tb_operacao");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Operacao record = (Operacao) parameter.get("record");
        OperacaoExample example = (OperacaoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("public.tb_operacao");
        
        if (record.getIdOperacao() != null) {
            sql.SET("id_operacao = #{record.idOperacao,jdbcType=OTHER}");
        }
        
        if (record.getDtOperacao() != null) {
            sql.SET("dt_operacao = #{record.dtOperacao,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIdTerminal() != null) {
            sql.SET("id_terminal = #{record.idTerminal,jdbcType=INTEGER}");
        }
        
        if (record.getIdUsuario() != null) {
            sql.SET("id_usuario = #{record.idUsuario,jdbcType=INTEGER}");
        }
        
        if (record.getIdTransacao() != null) {
            sql.SET("id_transacao = #{record.idTransacao,jdbcType=INTEGER}");
        }
        
        if (record.getVlOperacao() != null) {
            sql.SET("vl_operacao = #{record.vlOperacao,jdbcType=DOUBLE}");
        }
        
        if (record.getCdMoeda() != null) {
            sql.SET("cd_moeda = #{record.cdMoeda,jdbcType=INTEGER}");
        }
        
        if (record.getTpOperacao() != null) {
            sql.SET("tp_operacao = #{record.tpOperacao,jdbcType=OTHER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_operacao");
        
        sql.SET("id_operacao = #{record.idOperacao,jdbcType=OTHER}");
        sql.SET("dt_operacao = #{record.dtOperacao,jdbcType=TIMESTAMP}");
        sql.SET("id_terminal = #{record.idTerminal,jdbcType=INTEGER}");
        sql.SET("id_usuario = #{record.idUsuario,jdbcType=INTEGER}");
        sql.SET("id_transacao = #{record.idTransacao,jdbcType=INTEGER}");
        sql.SET("vl_operacao = #{record.vlOperacao,jdbcType=DOUBLE}");
        sql.SET("cd_moeda = #{record.cdMoeda,jdbcType=INTEGER}");
        sql.SET("tp_operacao = #{record.tpOperacao,jdbcType=OTHER}");
        
        OperacaoExample example = (OperacaoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    public String updateByPrimaryKeySelective(Operacao record) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_operacao");
        
        if (record.getDtOperacao() != null) {
            sql.SET("dt_operacao = #{dtOperacao,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIdTerminal() != null) {
            sql.SET("id_terminal = #{idTerminal,jdbcType=INTEGER}");
        }
        
        if (record.getIdUsuario() != null) {
            sql.SET("id_usuario = #{idUsuario,jdbcType=INTEGER}");
        }
        
        if (record.getIdTransacao() != null) {
            sql.SET("id_transacao = #{idTransacao,jdbcType=INTEGER}");
        }
        
        if (record.getVlOperacao() != null) {
            sql.SET("vl_operacao = #{vlOperacao,jdbcType=DOUBLE}");
        }
        
        if (record.getCdMoeda() != null) {
            sql.SET("cd_moeda = #{cdMoeda,jdbcType=INTEGER}");
        }
        
        if (record.getTpOperacao() != null) {
            sql.SET("tp_operacao = #{tpOperacao,jdbcType=OTHER}");
        }
        
        sql.WHERE("id_operacao = #{idOperacao,jdbcType=OTHER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_operacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    protected void applyWhere(SQL sql, OperacaoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}