package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.AcessoUsuarioRegiao;
import br.inf.orion.eSafe.client.model.example.TbAcessoUsuarioRegiaoExample;
import br.inf.orion.eSafe.client.service.provider.AcessoUsuarioRegiaoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AcessoUsuarioRegiaoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "countByExample")
	long countByExample(TbAcessoUsuarioRegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbAcessoUsuarioRegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_acesso_usuario_regiao", "where id_usuario = #{idUsuario,jdbcType=INTEGER}",
			"and id_regiao = #{idRegiao,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(AcessoUsuarioRegiao key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_acesso_usuario_regiao (id_usuario, id_regiao)",
			"values (#{idUsuario,jdbcType=INTEGER}, #{idRegiao,jdbcType=INTEGER})" })
	int insert(AcessoUsuarioRegiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "insertSelective")
	int insertSelective(AcessoUsuarioRegiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_usuario", property = "idUsuario", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_regiao", property = "idRegiao", jdbcType = JdbcType.INTEGER, id = true) })
	List<AcessoUsuarioRegiao> selectByExample(TbAcessoUsuarioRegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") AcessoUsuarioRegiao record,
			@Param("example") TbAcessoUsuarioRegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_acesso_usuario_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = AcessoUsuarioRegiaoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") AcessoUsuarioRegiao record,
			@Param("example") TbAcessoUsuarioRegiaoExample example);
}