package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.EnderecoEstabelecimento;
import br.inf.orion.eSafe.client.model.EnderecoEstabelecimentoKey;
import br.inf.orion.eSafe.client.model.example.TbEnderecoEstabelecimentoExample;
import br.inf.orion.eSafe.client.service.provider.EnderecoEstabelecimentoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EnderecoEstabelecimentoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "countByExample")
	long countByExample(TbEnderecoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbEnderecoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_endereco_estabelecimento",
			"where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}",
			"and id_endereco = #{idEndereco,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(EnderecoEstabelecimentoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_endereco_estabelecimento (id_estabelecimento, id_endereco, ",
			"tp_endereco, ds_logradouro, ", "ds_complemento, ds_bairro, ", "ds_cidade, ds_estado, ",
			"ds_codigo_postal)", "values (#{idEstabelecimento,jdbcType=INTEGER}, #{idEndereco,jdbcType=INTEGER}, ",
			"#{tpEndereco,jdbcType=INTEGER}, #{dsLogradouro,jdbcType=VARCHAR}, ",
			"#{dsComplemento,jdbcType=VARCHAR}, #{dsBairro,jdbcType=VARCHAR}, ",
			"#{dsCidade,jdbcType=VARCHAR}, #{dsEstado,jdbcType=CHAR}, ", "#{dsCodigoPostal,jdbcType=CHAR})" })
	int insert(EnderecoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "insertSelective")
	int insertSelective(EnderecoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_endereco", property = "idEndereco", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "tp_endereco", property = "tpEndereco", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_logradouro", property = "dsLogradouro", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_complemento", property = "dsComplemento", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_bairro", property = "dsBairro", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cidade", property = "dsCidade", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_estado", property = "dsEstado", jdbcType = JdbcType.CHAR),
			@Result(column = "ds_codigo_postal", property = "dsCodigoPostal", jdbcType = JdbcType.CHAR) })
	List<EnderecoEstabelecimento> selectByExample(TbEnderecoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_estabelecimento, id_endereco, tp_endereco, ds_logradouro, ds_complemento, ",
			"ds_bairro, ds_cidade, ds_estado, ds_codigo_postal", "from public.tb_endereco_estabelecimento",
			"where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}",
			"and id_endereco = #{idEndereco,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id_estabelecimento", property = "idEstabelecimento", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_endereco", property = "idEndereco", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "tp_endereco", property = "tpEndereco", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_logradouro", property = "dsLogradouro", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_complemento", property = "dsComplemento", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_bairro", property = "dsBairro", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cidade", property = "dsCidade", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_estado", property = "dsEstado", jdbcType = JdbcType.CHAR),
			@Result(column = "ds_codigo_postal", property = "dsCodigoPostal", jdbcType = JdbcType.CHAR) })
	EnderecoEstabelecimento selectByPrimaryKey(EnderecoEstabelecimentoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") EnderecoEstabelecimento record,
			@Param("example") TbEnderecoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") EnderecoEstabelecimento record,
			@Param("example") TbEnderecoEstabelecimentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = EnderecoEstabelecimentoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(EnderecoEstabelecimento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_endereco_estabelecimento", "set tp_endereco = #{tpEndereco,jdbcType=INTEGER},",
			"ds_logradouro = #{dsLogradouro,jdbcType=VARCHAR},", "ds_complemento = #{dsComplemento,jdbcType=VARCHAR},",
			"ds_bairro = #{dsBairro,jdbcType=VARCHAR},", "ds_cidade = #{dsCidade,jdbcType=VARCHAR},",
			"ds_estado = #{dsEstado,jdbcType=CHAR},", "ds_codigo_postal = #{dsCodigoPostal,jdbcType=CHAR}",
			"where id_estabelecimento = #{idEstabelecimento,jdbcType=INTEGER}",
			"and id_endereco = #{idEndereco,jdbcType=INTEGER}" })
	int updateByPrimaryKey(EnderecoEstabelecimento record);
}