package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Fabricante;
import br.inf.orion.eSafe.client.model.example.FabricanteExample;
import br.inf.orion.eSafe.client.service.provider.FabricanteSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FabricanteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FabricanteSqlProvider.class, method = "countByExample")
	long countByExample(FabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = FabricanteSqlProvider.class, method = "deleteByExample")
	int deleteByExample(FabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_fabricante", "where id_fabricante = #{idFabricante,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idFabricante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_fabricante (id_fabricante, ds_fabricante, ", "ds_cnpj, ic_ativo)",
			"values (#{idFabricante,jdbcType=INTEGER}, #{dsFabricante,jdbcType=VARCHAR}, ",
			"#{dsCnpj,jdbcType=VARCHAR}, #{icAtivo,jdbcType=BIT})" })
	int insert(Fabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = FabricanteSqlProvider.class, method = "insertSelective")
	int insertSelective(Fabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FabricanteSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_fabricante", property = "idFabricante", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_fabricante", property = "dsFabricante", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cnpj", property = "dsCnpj", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	List<Fabricante> selectByExample(FabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_fabricante, ds_fabricante, ds_cnpj, ic_ativo", "from public.tb_fabricante",
			"where id_fabricante = #{idFabricante,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_fabricante", property = "idFabricante", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_fabricante", property = "dsFabricante", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cnpj", property = "dsCnpj", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	Fabricante selectByPrimaryKey(Integer idFabricante);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FabricanteSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Fabricante record, @Param("example") FabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FabricanteSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Fabricante record, @Param("example") FabricanteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FabricanteSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Fabricante record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fabricante
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_fabricante", "set ds_fabricante = #{dsFabricante,jdbcType=VARCHAR},",
			"ds_cnpj = #{dsCnpj,jdbcType=VARCHAR},", "ic_ativo = #{icAtivo,jdbcType=BIT}",
			"where id_fabricante = #{idFabricante,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Fabricante record);
}