package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Filial;
import br.inf.orion.eSafe.client.model.example.FilialExample;
import br.inf.orion.eSafe.client.service.provider.FilialSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FilialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FilialSqlProvider.class, method = "countByExample")
	long countByExample(FilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = FilialSqlProvider.class, method = "deleteByExample")
	int deleteByExample(FilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_filial", "where id_filial = #{idFilial,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idFilial);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_filial (id_filial, id_regiao, ", "ds_filial, ic_ativo)",
			"values (#{idFilial,jdbcType=INTEGER}, #{idRegiao,jdbcType=INTEGER}, ",
			"#{dsFilial,jdbcType=VARCHAR}, #{icAtivo,jdbcType=BIT})" })
	int insert(Filial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = FilialSqlProvider.class, method = "insertSelective")
	int insertSelective(Filial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FilialSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_filial", property = "idFilial", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_regiao", property = "idRegiao", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_filial", property = "dsFilial", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	List<Filial> selectByExample(FilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_filial, id_regiao, ds_filial, ic_ativo", "from public.tb_filial",
			"where id_filial = #{idFilial,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_filial", property = "idFilial", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_regiao", property = "idRegiao", jdbcType = JdbcType.INTEGER),
			@Result(column = "ds_filial", property = "dsFilial", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	Filial selectByPrimaryKey(Integer idFilial);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FilialSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Filial record, @Param("example") FilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FilialSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Filial record, @Param("example") FilialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FilialSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Filial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_filial
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_filial", "set id_regiao = #{idRegiao,jdbcType=INTEGER},",
			"ds_filial = #{dsFilial,jdbcType=VARCHAR},", "ic_ativo = #{icAtivo,jdbcType=BIT}",
			"where id_filial = #{idFilial,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Filial record);
}