package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Fornecedor;
import br.inf.orion.eSafe.client.model.example.TbFornecedorExample;
import br.inf.orion.eSafe.client.service.provider.FornecedorSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FornecedorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FornecedorSqlProvider.class, method = "countByExample")
	long countByExample(TbFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = FornecedorSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_fornecedor", "where id_fornecedor = #{idFornecedor,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idFornecedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_fornecedor (id_fornecedor, ds_fornecedor, ", "ds_cnpj, ic_ativo)",
			"values (#{idFornecedor,jdbcType=INTEGER}, #{dsFornecedor,jdbcType=VARCHAR}, ",
			"#{dsCnpj,jdbcType=VARCHAR}, #{icAtivo,jdbcType=BIT})" })
	int insert(Fornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = FornecedorSqlProvider.class, method = "insertSelective")
	int insertSelective(Fornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = FornecedorSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_fornecedor", property = "dsFornecedor", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cnpj", property = "dsCnpj", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	List<Fornecedor> selectByExample(TbFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_fornecedor, ds_fornecedor, ds_cnpj, ic_ativo", "from public.tb_fornecedor",
			"where id_fornecedor = #{idFornecedor,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_fornecedor", property = "idFornecedor", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_fornecedor", property = "dsFornecedor", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_cnpj", property = "dsCnpj", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	Fornecedor selectByPrimaryKey(Integer idFornecedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FornecedorSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Fornecedor record, @Param("example") TbFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FornecedorSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Fornecedor record, @Param("example") TbFornecedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = FornecedorSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Fornecedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_fornecedor", "set ds_fornecedor = #{dsFornecedor,jdbcType=VARCHAR},",
			"ds_cnpj = #{dsCnpj,jdbcType=VARCHAR},", "ic_ativo = #{icAtivo,jdbcType=BIT}",
			"where id_fornecedor = #{idFornecedor,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Fornecedor record);
}