package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Moeda;
import br.inf.orion.eSafe.client.model.example.MoedaExample;
import br.inf.orion.eSafe.client.service.provider.MoedaSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MoedaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=MoedaSqlProvider.class, method="countByExample")
    long countByExample(MoedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @DeleteProvider(type=MoedaSqlProvider.class, method="deleteByExample")
    int deleteByExample(MoedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Delete({
        "delete from public.tb_moeda",
        "where cd_moeda = #{cdMoeda,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cdMoeda);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Insert({
        "insert into public.tb_moeda (cd_moeda, ds_simbolo, ",
        "ds_sigla, tp_conversao, ",
        "dt_exclusao)",
        "values (#{cdMoeda,jdbcType=INTEGER}, #{dsSimbolo,jdbcType=VARCHAR}, ",
        "#{dsSigla,jdbcType=VARCHAR}, #{tpConversao,jdbcType=CHAR}, ",
        "#{dtExclusao,jdbcType=DATE})"
    })
    int insert(Moeda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @InsertProvider(type=MoedaSqlProvider.class, method="insertSelective")
    int insertSelective(Moeda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=MoedaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="cd_moeda", property="cdMoeda", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_simbolo", property="dsSimbolo", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_sigla", property="dsSigla", jdbcType=JdbcType.VARCHAR),
        @Result(column="tp_conversao", property="tpConversao", jdbcType=JdbcType.CHAR),
        @Result(column="dt_exclusao", property="dtExclusao", jdbcType=JdbcType.DATE)
    })
    List<Moeda> selectByExample(MoedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Select({
        "select",
        "cd_moeda, ds_simbolo, ds_sigla, tp_conversao, dt_exclusao",
        "from public.tb_moeda",
        "where cd_moeda = #{cdMoeda,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cd_moeda", property="cdMoeda", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_simbolo", property="dsSimbolo", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_sigla", property="dsSigla", jdbcType=JdbcType.VARCHAR),
        @Result(column="tp_conversao", property="tpConversao", jdbcType=JdbcType.CHAR),
        @Result(column="dt_exclusao", property="dtExclusao", jdbcType=JdbcType.DATE)
    })
    Moeda selectByPrimaryKey(Integer cdMoeda);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=MoedaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Moeda record, @Param("example") MoedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=MoedaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Moeda record, @Param("example") MoedaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=MoedaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Moeda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_moeda
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Update({
        "update public.tb_moeda",
        "set ds_simbolo = #{dsSimbolo,jdbcType=VARCHAR},",
          "ds_sigla = #{dsSigla,jdbcType=VARCHAR},",
          "tp_conversao = #{tpConversao,jdbcType=CHAR},",
          "dt_exclusao = #{dtExclusao,jdbcType=DATE}",
        "where cd_moeda = #{cdMoeda,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Moeda record);
}