package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Monitoracao;
import br.inf.orion.eSafe.client.model.example.MonitoracaoExample;
import br.inf.orion.eSafe.client.service.provider.MonitoracaoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MonitoracaoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@SelectProvider(type = MonitoracaoSqlProvider.class, method = "countByExample")
	long countByExample(MonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@DeleteProvider(type = MonitoracaoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(MonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Delete({ "delete from public.tb_monitoracao", "where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idTerminal);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Insert({ "insert into public.tb_monitoracao (id_terminal, dt_envio, ", "ic_status_terminal, id_monitoracao)",
			"values (#{idTerminal,jdbcType=INTEGER}, #{dtEnvio,jdbcType=TIMESTAMP}, ",
			"#{icStatusTerminal,jdbcType=INTEGER}, #{idMonitoracao,jdbcType=OTHER})" })
	int insert(Monitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@InsertProvider(type = MonitoracaoSqlProvider.class, method = "insertSelective")
	int insertSelective(Monitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@SelectProvider(type = MonitoracaoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "dt_envio", property = "dtEnvio", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ic_status_terminal", property = "icStatusTerminal", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_monitoracao", property = "idMonitoracao", jdbcType = JdbcType.OTHER) })
	List<Monitoracao> selectByExample(MonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Select({ "select", "id_terminal, dt_envio, ic_status_terminal, id_monitoracao", "from public.tb_monitoracao",
			"where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "dt_envio", property = "dtEnvio", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ic_status_terminal", property = "icStatusTerminal", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_monitoracao", property = "idMonitoracao", jdbcType = JdbcType.OTHER) })
	Monitoracao selectByPrimaryKey(Integer idTerminal);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = MonitoracaoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Monitoracao record, @Param("example") MonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = MonitoracaoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Monitoracao record, @Param("example") MonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = MonitoracaoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Monitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_monitoracao
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Update({ "update public.tb_monitoracao", "set dt_envio = #{dtEnvio,jdbcType=TIMESTAMP},",
			"ic_status_terminal = #{icStatusTerminal,jdbcType=INTEGER},",
			"id_monitoracao = #{idMonitoracao,jdbcType=OTHER}", "where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Monitoracao record);
}