package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Pais;
import br.inf.orion.eSafe.client.model.example.PaisExample;
import br.inf.orion.eSafe.client.service.provider.PaisSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PaisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=PaisSqlProvider.class, method="countByExample")
    long countByExample(PaisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @DeleteProvider(type=PaisSqlProvider.class, method="deleteByExample")
    int deleteByExample(PaisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Delete({
        "delete from public.tb_pais",
        "where cd_pais = #{cdPais,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cdPais);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Insert({
        "insert into public.tb_pais (cd_pais, ds_pais, ",
        "ds_nome, cd_moeda)",
        "values (#{cdPais,jdbcType=INTEGER}, #{dsPais,jdbcType=VARCHAR}, ",
        "#{dsNome,jdbcType=VARCHAR}, #{cdMoeda,jdbcType=INTEGER})"
    })
    int insert(Pais record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @InsertProvider(type=PaisSqlProvider.class, method="insertSelective")
    int insertSelective(Pais record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=PaisSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="cd_pais", property="cdPais", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_pais", property="dsPais", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_nome", property="dsNome", jdbcType=JdbcType.VARCHAR),
        @Result(column="cd_moeda", property="cdMoeda", jdbcType=JdbcType.INTEGER)
    })
    List<Pais> selectByExample(PaisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Select({
        "select",
        "cd_pais, ds_pais, ds_nome, cd_moeda",
        "from public.tb_pais",
        "where cd_pais = #{cdPais,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cd_pais", property="cdPais", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_pais", property="dsPais", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_nome", property="dsNome", jdbcType=JdbcType.VARCHAR),
        @Result(column="cd_moeda", property="cdMoeda", jdbcType=JdbcType.INTEGER)
    })
    Pais selectByPrimaryKey(Integer cdPais);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=PaisSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Pais record, @Param("example") PaisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=PaisSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Pais record, @Param("example") PaisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=PaisSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Pais record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_pais
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Update({
        "update public.tb_pais",
        "set ds_pais = #{dsPais,jdbcType=VARCHAR},",
          "ds_nome = #{dsNome,jdbcType=VARCHAR},",
          "cd_moeda = #{cdMoeda,jdbcType=INTEGER}",
        "where cd_pais = #{cdPais,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Pais record);
}