package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Regiao;
import br.inf.orion.eSafe.client.model.example.RegiaoExample;
import br.inf.orion.eSafe.client.service.provider.RegiaoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RegiaoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = RegiaoSqlProvider.class, method = "countByExample")
	long countByExample(RegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = RegiaoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(RegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_regiao", "where id_regiao = #{idRegiao,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idRegiao);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_regiao (id_regiao, ds_regiao, ", "ic_ativo)",
			"values (#{idRegiao,jdbcType=INTEGER}, #{dsRegiao,jdbcType=VARCHAR}, ", "#{icAtivo,jdbcType=BIT})" })
	int insert(Regiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = RegiaoSqlProvider.class, method = "insertSelective")
	int insertSelective(Regiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = RegiaoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_regiao", property = "idRegiao", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_regiao", property = "dsRegiao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	List<Regiao> selectByExample(RegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_regiao, ds_regiao, ic_ativo", "from public.tb_regiao",
			"where id_regiao = #{idRegiao,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_regiao", property = "idRegiao", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_regiao", property = "dsRegiao", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT) })
	Regiao selectByPrimaryKey(Integer idRegiao);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = RegiaoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Regiao record, @Param("example") RegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = RegiaoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Regiao record, @Param("example") RegiaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = RegiaoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Regiao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_regiao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_regiao", "set ds_regiao = #{dsRegiao,jdbcType=VARCHAR},",
			"ic_ativo = #{icAtivo,jdbcType=BIT}", "where id_regiao = #{idRegiao,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Regiao record);
}