package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Sensor;
import br.inf.orion.eSafe.client.model.SensorKey;
import br.inf.orion.eSafe.client.model.example.SensorExample;
import br.inf.orion.eSafe.client.service.provider.SensorSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SensorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@SelectProvider(type = SensorSqlProvider.class, method = "countByExample")
	long countByExample(SensorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@DeleteProvider(type = SensorSqlProvider.class, method = "deleteByExample")
	int deleteByExample(SensorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Delete({ "delete from public.tb_sensor", "where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}",
			"and id_sensor = #{idSensor,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(SensorKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Insert({ "insert into public.tb_sensor (id_dispositivo, id_sensor, ", "ds_sensor)",
			"values (#{idDispositivo,jdbcType=INTEGER}, #{idSensor,jdbcType=INTEGER}, ",
			"#{dsSensor,jdbcType=VARCHAR})" })
	int insert(Sensor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@InsertProvider(type = SensorSqlProvider.class, method = "insertSelective")
	int insertSelective(Sensor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@SelectProvider(type = SensorSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_sensor", property = "idSensor", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_sensor", property = "dsSensor", jdbcType = JdbcType.VARCHAR) })
	List<Sensor> selectByExample(SensorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Select({ "select", "id_dispositivo, id_sensor, ds_sensor", "from public.tb_sensor",
			"where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}",
			"and id_sensor = #{idSensor,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_sensor", property = "idSensor", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_sensor", property = "dsSensor", jdbcType = JdbcType.VARCHAR) })
	Sensor selectByPrimaryKey(SensorKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = SensorSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Sensor record, @Param("example") SensorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = SensorSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Sensor record, @Param("example") SensorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@UpdateProvider(type = SensorSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Sensor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	@Update({ "update public.tb_sensor", "set ds_sensor = #{dsSensor,jdbcType=VARCHAR}",
			"where id_dispositivo = #{idDispositivo,jdbcType=INTEGER}",
			"and id_sensor = #{idSensor,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Sensor record);
}