package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.StatusMonitoracao;
import br.inf.orion.eSafe.client.model.StatusMonitoracaoKey;
import br.inf.orion.eSafe.client.model.example.StatusMonitoracaoExample;
import br.inf.orion.eSafe.client.service.provider.StatusMonitoracaoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StatusMonitoracaoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = StatusMonitoracaoSqlProvider.class, method = "countByExample")
	long countByExample(StatusMonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = StatusMonitoracaoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StatusMonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_status_monitoracao", "where id_terminal = #{idTerminal,jdbcType=INTEGER}",
			"and id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(StatusMonitoracaoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_status_monitoracao (id_terminal, id_dispositivo, ", "cd_status)",
			"values (#{idTerminal,jdbcType=INTEGER}, #{idDispositivo,jdbcType=INTEGER}, ",
			"#{cdStatus,jdbcType=INTEGER})" })
	int insert(StatusMonitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = StatusMonitoracaoSqlProvider.class, method = "insertSelective")
	int insertSelective(StatusMonitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = StatusMonitoracaoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "cd_status", property = "cdStatus", jdbcType = JdbcType.INTEGER) })
	List<StatusMonitoracao> selectByExample(StatusMonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_terminal, id_dispositivo, cd_status", "from public.tb_status_monitoracao",
			"where id_terminal = #{idTerminal,jdbcType=INTEGER}",
			"and id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_dispositivo", property = "idDispositivo", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "cd_status", property = "cdStatus", jdbcType = JdbcType.INTEGER) })
	StatusMonitoracao selectByPrimaryKey(StatusMonitoracaoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = StatusMonitoracaoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StatusMonitoracao record,
			@Param("example") StatusMonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = StatusMonitoracaoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StatusMonitoracao record,
			@Param("example") StatusMonitoracaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = StatusMonitoracaoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StatusMonitoracao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_monitoracao
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_status_monitoracao", "set cd_status = #{cdStatus,jdbcType=INTEGER}",
			"where id_terminal = #{idTerminal,jdbcType=INTEGER}",
			"and id_dispositivo = #{idDispositivo,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StatusMonitoracao record);
}