package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.Transacao;
import br.inf.orion.eSafe.client.model.example.TransacaoExample;
import br.inf.orion.eSafe.client.service.provider.TransacaoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TransacaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=TransacaoSqlProvider.class, method="countByExample")
    long countByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @DeleteProvider(type=TransacaoSqlProvider.class, method="deleteByExample")
    int deleteByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Delete({
        "delete from public.tb_transacao",
        "where id_transacao = #{idTransacao,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idTransacao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Insert({
        "insert into public.tb_transacao (id_transacao, ds_transacao)",
        "values (#{idTransacao,jdbcType=INTEGER}, #{dsTransacao,jdbcType=VARCHAR})"
    })
    int insert(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @InsertProvider(type=TransacaoSqlProvider.class, method="insertSelective")
    int insertSelective(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @SelectProvider(type=TransacaoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_transacao", property="idTransacao", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_transacao", property="dsTransacao", jdbcType=JdbcType.VARCHAR)
    })
    List<Transacao> selectByExample(TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Select({
        "select",
        "id_transacao, ds_transacao",
        "from public.tb_transacao",
        "where id_transacao = #{idTransacao,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_transacao", property="idTransacao", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_transacao", property="dsTransacao", jdbcType=JdbcType.VARCHAR)
    })
    Transacao selectByPrimaryKey(Integer idTransacao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=TransacaoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Transacao record, @Param("example") TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=TransacaoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Transacao record, @Param("example") TransacaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @UpdateProvider(type=TransacaoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Transacao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_transacao
     *
     * @mbg.generated Wed Dec 28 01:55:16 BRST 2016
     */
    @Update({
        "update public.tb_transacao",
        "set ds_transacao = #{dsTransacao,jdbcType=VARCHAR}",
        "where id_transacao = #{idTransacao,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Transacao record);
}