package br.inf.orion.eSafe.client.model.mapper;

import br.inf.orion.eSafe.client.model.UsuarioExterno;
import br.inf.orion.eSafe.client.model.example.TbUsuarioExternoExample;
import br.inf.orion.eSafe.client.service.provider.UsuarioExternoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsuarioExternoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = UsuarioExternoSqlProvider.class, method = "countByExample")
	long countByExample(TbUsuarioExternoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@DeleteProvider(type = UsuarioExternoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbUsuarioExternoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Delete({ "delete from public.tb_usuario_externo", "where id_usuario = #{idUsuario,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idUsuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Insert({ "insert into public.tb_usuario_externo (id_usuario, ds_login, ", "ds_nome, id_detalhe, ",
			"ic_ativo, dt_inclusao)", "values (#{idUsuario,jdbcType=INTEGER}, #{dsLogin,jdbcType=VARCHAR}, ",
			"#{dsNome,jdbcType=VARCHAR}, #{idDetalhe,jdbcType=VARCHAR}, ",
			"#{icAtivo,jdbcType=BIT}, #{dtInclusao,jdbcType=TIMESTAMP})" })
	int insert(UsuarioExterno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@InsertProvider(type = UsuarioExternoSqlProvider.class, method = "insertSelective")
	int insertSelective(UsuarioExterno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@SelectProvider(type = UsuarioExternoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_usuario", property = "idUsuario", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_login", property = "dsLogin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_nome", property = "dsNome", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_detalhe", property = "idDetalhe", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT),
			@Result(column = "dt_inclusao", property = "dtInclusao", jdbcType = JdbcType.TIMESTAMP) })
	List<UsuarioExterno> selectByExample(TbUsuarioExternoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Select({ "select", "id_usuario, ds_login, ds_nome, id_detalhe, ic_ativo, dt_inclusao",
			"from public.tb_usuario_externo", "where id_usuario = #{idUsuario,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_usuario", property = "idUsuario", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_login", property = "dsLogin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_nome", property = "dsNome", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_detalhe", property = "idDetalhe", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT),
			@Result(column = "dt_inclusao", property = "dtInclusao", jdbcType = JdbcType.TIMESTAMP) })
	UsuarioExterno selectByPrimaryKey(Integer idUsuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = UsuarioExternoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") UsuarioExterno record,
			@Param("example") TbUsuarioExternoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = UsuarioExternoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") UsuarioExterno record, @Param("example") TbUsuarioExternoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@UpdateProvider(type = UsuarioExternoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(UsuarioExterno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario_externo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	@Update({ "update public.tb_usuario_externo", "set ds_login = #{dsLogin,jdbcType=VARCHAR},",
			"ds_nome = #{dsNome,jdbcType=VARCHAR},", "id_detalhe = #{idDetalhe,jdbcType=VARCHAR},",
			"ic_ativo = #{icAtivo,jdbcType=BIT},", "dt_inclusao = #{dtInclusao,jdbcType=TIMESTAMP}",
			"where id_usuario = #{idUsuario,jdbcType=INTEGER}" })
	int updateByPrimaryKey(UsuarioExterno record);
}