package br.inf.orion.eSafe.model.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClienteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public ClienteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdClienteIsNull() {
			addCriterion("id_cliente is null");
			return (Criteria) this;
		}

		public Criteria andIdClienteIsNotNull() {
			addCriterion("id_cliente is not null");
			return (Criteria) this;
		}

		public Criteria andIdClienteEqualTo(Integer value) {
			addCriterion("id_cliente =", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotEqualTo(Integer value) {
			addCriterion("id_cliente <>", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteGreaterThan(Integer value) {
			addCriterion("id_cliente >", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_cliente >=", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteLessThan(Integer value) {
			addCriterion("id_cliente <", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteLessThanOrEqualTo(Integer value) {
			addCriterion("id_cliente <=", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteIn(List<Integer> values) {
			addCriterion("id_cliente in", values, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotIn(List<Integer> values) {
			addCriterion("id_cliente not in", values, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteBetween(Integer value1, Integer value2) {
			addCriterion("id_cliente between", value1, value2, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotBetween(Integer value1, Integer value2) {
			addCriterion("id_cliente not between", value1, value2, "idCliente");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaIsNull() {
			addCriterion("ds_nome_fantasia is null");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaIsNotNull() {
			addCriterion("ds_nome_fantasia is not null");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaEqualTo(String value) {
			addCriterion("ds_nome_fantasia =", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaNotEqualTo(String value) {
			addCriterion("ds_nome_fantasia <>", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaGreaterThan(String value) {
			addCriterion("ds_nome_fantasia >", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaGreaterThanOrEqualTo(String value) {
			addCriterion("ds_nome_fantasia >=", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaLessThan(String value) {
			addCriterion("ds_nome_fantasia <", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaLessThanOrEqualTo(String value) {
			addCriterion("ds_nome_fantasia <=", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaLike(String value) {
			addCriterion("ds_nome_fantasia like", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaNotLike(String value) {
			addCriterion("ds_nome_fantasia not like", value, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaIn(List<String> values) {
			addCriterion("ds_nome_fantasia in", values, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaNotIn(List<String> values) {
			addCriterion("ds_nome_fantasia not in", values, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaBetween(String value1, String value2) {
			addCriterion("ds_nome_fantasia between", value1, value2, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsNomeFantasiaNotBetween(String value1, String value2) {
			addCriterion("ds_nome_fantasia not between", value1, value2, "dsNomeFantasia");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialIsNull() {
			addCriterion("ds_razao_social is null");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialIsNotNull() {
			addCriterion("ds_razao_social is not null");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialEqualTo(String value) {
			addCriterion("ds_razao_social =", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialNotEqualTo(String value) {
			addCriterion("ds_razao_social <>", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialGreaterThan(String value) {
			addCriterion("ds_razao_social >", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialGreaterThanOrEqualTo(String value) {
			addCriterion("ds_razao_social >=", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialLessThan(String value) {
			addCriterion("ds_razao_social <", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialLessThanOrEqualTo(String value) {
			addCriterion("ds_razao_social <=", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialLike(String value) {
			addCriterion("ds_razao_social like", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialNotLike(String value) {
			addCriterion("ds_razao_social not like", value, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialIn(List<String> values) {
			addCriterion("ds_razao_social in", values, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialNotIn(List<String> values) {
			addCriterion("ds_razao_social not in", values, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialBetween(String value1, String value2) {
			addCriterion("ds_razao_social between", value1, value2, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsRazaoSocialNotBetween(String value1, String value2) {
			addCriterion("ds_razao_social not between", value1, value2, "dsRazaoSocial");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIsNull() {
			addCriterion("ds_cnpj is null");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIsNotNull() {
			addCriterion("ds_cnpj is not null");
			return (Criteria) this;
		}

		public Criteria andDsCnpjEqualTo(String value) {
			addCriterion("ds_cnpj =", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotEqualTo(String value) {
			addCriterion("ds_cnpj <>", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjGreaterThan(String value) {
			addCriterion("ds_cnpj >", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjGreaterThanOrEqualTo(String value) {
			addCriterion("ds_cnpj >=", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLessThan(String value) {
			addCriterion("ds_cnpj <", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLessThanOrEqualTo(String value) {
			addCriterion("ds_cnpj <=", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLike(String value) {
			addCriterion("ds_cnpj like", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotLike(String value) {
			addCriterion("ds_cnpj not like", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIn(List<String> values) {
			addCriterion("ds_cnpj in", values, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotIn(List<String> values) {
			addCriterion("ds_cnpj not in", values, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjBetween(String value1, String value2) {
			addCriterion("ds_cnpj between", value1, value2, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotBetween(String value1, String value2) {
			addCriterion("ds_cnpj not between", value1, value2, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDtCadastroIsNull() {
			addCriterion("dt_cadastro is null");
			return (Criteria) this;
		}

		public Criteria andDtCadastroIsNotNull() {
			addCriterion("dt_cadastro is not null");
			return (Criteria) this;
		}

		public Criteria andDtCadastroEqualTo(Date value) {
			addCriterion("dt_cadastro =", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroNotEqualTo(Date value) {
			addCriterion("dt_cadastro <>", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroGreaterThan(Date value) {
			addCriterion("dt_cadastro >", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroGreaterThanOrEqualTo(Date value) {
			addCriterion("dt_cadastro >=", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroLessThan(Date value) {
			addCriterion("dt_cadastro <", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroLessThanOrEqualTo(Date value) {
			addCriterion("dt_cadastro <=", value, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroIn(List<Date> values) {
			addCriterion("dt_cadastro in", values, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroNotIn(List<Date> values) {
			addCriterion("dt_cadastro not in", values, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroBetween(Date value1, Date value2) {
			addCriterion("dt_cadastro between", value1, value2, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andDtCadastroNotBetween(Date value1, Date value2) {
			addCriterion("dt_cadastro not between", value1, value2, "dtCadastro");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNull() {
			addCriterion("ic_ativo is null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNotNull() {
			addCriterion("ic_ativo is not null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoEqualTo(Boolean value) {
			addCriterion("ic_ativo =", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotEqualTo(Boolean value) {
			addCriterion("ic_ativo <>", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThan(Boolean value) {
			addCriterion("ic_ativo >", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo >=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThan(Boolean value) {
			addCriterion("ic_ativo <", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo <=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIn(List<Boolean> values) {
			addCriterion("ic_ativo in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotIn(List<Boolean> values) {
			addCriterion("ic_ativo not in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo between", value1, value2, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo not between", value1, value2, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andDsConexaoIsNull() {
			addCriterion("ds_conexao is null");
			return (Criteria) this;
		}

		public Criteria andDsConexaoIsNotNull() {
			addCriterion("ds_conexao is not null");
			return (Criteria) this;
		}

		public Criteria andDsConexaoEqualTo(String value) {
			addCriterion("ds_conexao =", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoNotEqualTo(String value) {
			addCriterion("ds_conexao <>", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoGreaterThan(String value) {
			addCriterion("ds_conexao >", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoGreaterThanOrEqualTo(String value) {
			addCriterion("ds_conexao >=", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoLessThan(String value) {
			addCriterion("ds_conexao <", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoLessThanOrEqualTo(String value) {
			addCriterion("ds_conexao <=", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoLike(String value) {
			addCriterion("ds_conexao like", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoNotLike(String value) {
			addCriterion("ds_conexao not like", value, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoIn(List<String> values) {
			addCriterion("ds_conexao in", values, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoNotIn(List<String> values) {
			addCriterion("ds_conexao not in", values, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoBetween(String value1, String value2) {
			addCriterion("ds_conexao between", value1, value2, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsConexaoNotBetween(String value1, String value2) {
			addCriterion("ds_conexao not between", value1, value2, "dsConexao");
			return (Criteria) this;
		}

		public Criteria andDsSiglaIsNull() {
			addCriterion("ds_sigla is null");
			return (Criteria) this;
		}

		public Criteria andDsSiglaIsNotNull() {
			addCriterion("ds_sigla is not null");
			return (Criteria) this;
		}

		public Criteria andDsSiglaEqualTo(String value) {
			addCriterion("ds_sigla =", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaNotEqualTo(String value) {
			addCriterion("ds_sigla <>", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaGreaterThan(String value) {
			addCriterion("ds_sigla >", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaGreaterThanOrEqualTo(String value) {
			addCriterion("ds_sigla >=", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaLessThan(String value) {
			addCriterion("ds_sigla <", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaLessThanOrEqualTo(String value) {
			addCriterion("ds_sigla <=", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaLike(String value) {
			addCriterion("ds_sigla like", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaNotLike(String value) {
			addCriterion("ds_sigla not like", value, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaIn(List<String> values) {
			addCriterion("ds_sigla in", values, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaNotIn(List<String> values) {
			addCriterion("ds_sigla not in", values, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaBetween(String value1, String value2) {
			addCriterion("ds_sigla between", value1, value2, "dsSigla");
			return (Criteria) this;
		}

		public Criteria andDsSiglaNotBetween(String value1, String value2) {
			addCriterion("ds_sigla not between", value1, value2, "dsSigla");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_cliente
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_cliente
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 22 22:26:41 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}