package br.inf.orion.eSafe.model.example;

import java.util.ArrayList;
import java.util.List;

public class FuncionalidadeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public FuncionalidadeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdFuncionalidadeIsNull() {
			addCriterion("id_funcionalidade is null");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeIsNotNull() {
			addCriterion("id_funcionalidade is not null");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeEqualTo(Integer value) {
			addCriterion("id_funcionalidade =", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeNotEqualTo(Integer value) {
			addCriterion("id_funcionalidade <>", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeGreaterThan(Integer value) {
			addCriterion("id_funcionalidade >", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_funcionalidade >=", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeLessThan(Integer value) {
			addCriterion("id_funcionalidade <", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeLessThanOrEqualTo(Integer value) {
			addCriterion("id_funcionalidade <=", value, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeIn(List<Integer> values) {
			addCriterion("id_funcionalidade in", values, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeNotIn(List<Integer> values) {
			addCriterion("id_funcionalidade not in", values, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeBetween(Integer value1, Integer value2) {
			addCriterion("id_funcionalidade between", value1, value2, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeNotBetween(Integer value1, Integer value2) {
			addCriterion("id_funcionalidade not between", value1, value2, "idFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeIsNull() {
			addCriterion("ds_funcionalidade is null");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeIsNotNull() {
			addCriterion("ds_funcionalidade is not null");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeEqualTo(String value) {
			addCriterion("ds_funcionalidade =", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeNotEqualTo(String value) {
			addCriterion("ds_funcionalidade <>", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeGreaterThan(String value) {
			addCriterion("ds_funcionalidade >", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeGreaterThanOrEqualTo(String value) {
			addCriterion("ds_funcionalidade >=", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeLessThan(String value) {
			addCriterion("ds_funcionalidade <", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeLessThanOrEqualTo(String value) {
			addCriterion("ds_funcionalidade <=", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeLike(String value) {
			addCriterion("ds_funcionalidade like", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeNotLike(String value) {
			addCriterion("ds_funcionalidade not like", value, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeIn(List<String> values) {
			addCriterion("ds_funcionalidade in", values, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeNotIn(List<String> values) {
			addCriterion("ds_funcionalidade not in", values, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeBetween(String value1, String value2) {
			addCriterion("ds_funcionalidade between", value1, value2, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsFuncionalidadeNotBetween(String value1, String value2) {
			addCriterion("ds_funcionalidade not between", value1, value2, "dsFuncionalidade");
			return (Criteria) this;
		}

		public Criteria andDsProgramaIsNull() {
			addCriterion("ds_programa is null");
			return (Criteria) this;
		}

		public Criteria andDsProgramaIsNotNull() {
			addCriterion("ds_programa is not null");
			return (Criteria) this;
		}

		public Criteria andDsProgramaEqualTo(String value) {
			addCriterion("ds_programa =", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaNotEqualTo(String value) {
			addCriterion("ds_programa <>", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaGreaterThan(String value) {
			addCriterion("ds_programa >", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaGreaterThanOrEqualTo(String value) {
			addCriterion("ds_programa >=", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaLessThan(String value) {
			addCriterion("ds_programa <", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaLessThanOrEqualTo(String value) {
			addCriterion("ds_programa <=", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaLike(String value) {
			addCriterion("ds_programa like", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaNotLike(String value) {
			addCriterion("ds_programa not like", value, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaIn(List<String> values) {
			addCriterion("ds_programa in", values, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaNotIn(List<String> values) {
			addCriterion("ds_programa not in", values, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaBetween(String value1, String value2) {
			addCriterion("ds_programa between", value1, value2, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andDsProgramaNotBetween(String value1, String value2) {
			addCriterion("ds_programa not between", value1, value2, "dsPrograma");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorIsNull() {
			addCriterion("id_funcionalidade_anterior is null");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorIsNotNull() {
			addCriterion("id_funcionalidade_anterior is not null");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorEqualTo(Integer value) {
			addCriterion("id_funcionalidade_anterior =", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorNotEqualTo(Integer value) {
			addCriterion("id_funcionalidade_anterior <>", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorGreaterThan(Integer value) {
			addCriterion("id_funcionalidade_anterior >", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_funcionalidade_anterior >=", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorLessThan(Integer value) {
			addCriterion("id_funcionalidade_anterior <", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorLessThanOrEqualTo(Integer value) {
			addCriterion("id_funcionalidade_anterior <=", value, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorIn(List<Integer> values) {
			addCriterion("id_funcionalidade_anterior in", values, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorNotIn(List<Integer> values) {
			addCriterion("id_funcionalidade_anterior not in", values, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorBetween(Integer value1, Integer value2) {
			addCriterion("id_funcionalidade_anterior between", value1, value2, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdFuncionalidadeAnteriorNotBetween(Integer value1, Integer value2) {
			addCriterion("id_funcionalidade_anterior not between", value1, value2, "idFuncionalidadeAnterior");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaIsNull() {
			addCriterion("id_sequencia is null");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaIsNotNull() {
			addCriterion("id_sequencia is not null");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaEqualTo(Integer value) {
			addCriterion("id_sequencia =", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaNotEqualTo(Integer value) {
			addCriterion("id_sequencia <>", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaGreaterThan(Integer value) {
			addCriterion("id_sequencia >", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sequencia >=", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaLessThan(Integer value) {
			addCriterion("id_sequencia <", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaLessThanOrEqualTo(Integer value) {
			addCriterion("id_sequencia <=", value, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaIn(List<Integer> values) {
			addCriterion("id_sequencia in", values, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaNotIn(List<Integer> values) {
			addCriterion("id_sequencia not in", values, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaBetween(Integer value1, Integer value2) {
			addCriterion("id_sequencia between", value1, value2, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSequenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sequencia not between", value1, value2, "idSequencia");
			return (Criteria) this;
		}

		public Criteria andIdSistemaIsNull() {
			addCriterion("id_sistema is null");
			return (Criteria) this;
		}

		public Criteria andIdSistemaIsNotNull() {
			addCriterion("id_sistema is not null");
			return (Criteria) this;
		}

		public Criteria andIdSistemaEqualTo(Integer value) {
			addCriterion("id_sistema =", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaNotEqualTo(Integer value) {
			addCriterion("id_sistema <>", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaGreaterThan(Integer value) {
			addCriterion("id_sistema >", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sistema >=", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaLessThan(Integer value) {
			addCriterion("id_sistema <", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaLessThanOrEqualTo(Integer value) {
			addCriterion("id_sistema <=", value, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaIn(List<Integer> values) {
			addCriterion("id_sistema in", values, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaNotIn(List<Integer> values) {
			addCriterion("id_sistema not in", values, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaBetween(Integer value1, Integer value2) {
			addCriterion("id_sistema between", value1, value2, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIdSistemaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sistema not between", value1, value2, "idSistema");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNull() {
			addCriterion("ic_ativo is null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNotNull() {
			addCriterion("ic_ativo is not null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoEqualTo(Boolean value) {
			addCriterion("ic_ativo =", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotEqualTo(Boolean value) {
			addCriterion("ic_ativo <>", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThan(Boolean value) {
			addCriterion("ic_ativo >", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo >=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThan(Boolean value) {
			addCriterion("ic_ativo <", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo <=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIn(List<Boolean> values) {
			addCriterion("ic_ativo in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotIn(List<Boolean> values) {
			addCriterion("ic_ativo not in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo between", value1, value2, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo not between", value1, value2, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andDsPathIsNull() {
			addCriterion("ds_path is null");
			return (Criteria) this;
		}

		public Criteria andDsPathIsNotNull() {
			addCriterion("ds_path is not null");
			return (Criteria) this;
		}

		public Criteria andDsPathEqualTo(String value) {
			addCriterion("ds_path =", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathNotEqualTo(String value) {
			addCriterion("ds_path <>", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathGreaterThan(String value) {
			addCriterion("ds_path >", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathGreaterThanOrEqualTo(String value) {
			addCriterion("ds_path >=", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathLessThan(String value) {
			addCriterion("ds_path <", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathLessThanOrEqualTo(String value) {
			addCriterion("ds_path <=", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathLike(String value) {
			addCriterion("ds_path like", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathNotLike(String value) {
			addCriterion("ds_path not like", value, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathIn(List<String> values) {
			addCriterion("ds_path in", values, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathNotIn(List<String> values) {
			addCriterion("ds_path not in", values, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathBetween(String value1, String value2) {
			addCriterion("ds_path between", value1, value2, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsPathNotBetween(String value1, String value2) {
			addCriterion("ds_path not between", value1, value2, "dsPath");
			return (Criteria) this;
		}

		public Criteria andDsIconeIsNull() {
			addCriterion("ds_icone is null");
			return (Criteria) this;
		}

		public Criteria andDsIconeIsNotNull() {
			addCriterion("ds_icone is not null");
			return (Criteria) this;
		}

		public Criteria andDsIconeEqualTo(String value) {
			addCriterion("ds_icone =", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeNotEqualTo(String value) {
			addCriterion("ds_icone <>", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeGreaterThan(String value) {
			addCriterion("ds_icone >", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeGreaterThanOrEqualTo(String value) {
			addCriterion("ds_icone >=", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeLessThan(String value) {
			addCriterion("ds_icone <", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeLessThanOrEqualTo(String value) {
			addCriterion("ds_icone <=", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeLike(String value) {
			addCriterion("ds_icone like", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeNotLike(String value) {
			addCriterion("ds_icone not like", value, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeIn(List<String> values) {
			addCriterion("ds_icone in", values, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeNotIn(List<String> values) {
			addCriterion("ds_icone not in", values, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeBetween(String value1, String value2) {
			addCriterion("ds_icone between", value1, value2, "dsIcone");
			return (Criteria) this;
		}

		public Criteria andDsIconeNotBetween(String value1, String value2) {
			addCriterion("ds_icone not between", value1, value2, "dsIcone");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_funcionalidade
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 22 23:42:57 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}