package br.inf.orion.eSafe.model.example;

import java.util.ArrayList;
import java.util.List;

public class FuncionalidadeClienteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public FuncionalidadeClienteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdFuncionalidadeIsNull() {
            addCriterion("id_funcionalidade is null");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeIsNotNull() {
            addCriterion("id_funcionalidade is not null");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeEqualTo(Integer value) {
            addCriterion("id_funcionalidade =", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeNotEqualTo(Integer value) {
            addCriterion("id_funcionalidade <>", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeGreaterThan(Integer value) {
            addCriterion("id_funcionalidade >", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_funcionalidade >=", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeLessThan(Integer value) {
            addCriterion("id_funcionalidade <", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeLessThanOrEqualTo(Integer value) {
            addCriterion("id_funcionalidade <=", value, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeIn(List<Integer> values) {
            addCriterion("id_funcionalidade in", values, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeNotIn(List<Integer> values) {
            addCriterion("id_funcionalidade not in", values, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeBetween(Integer value1, Integer value2) {
            addCriterion("id_funcionalidade between", value1, value2, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdFuncionalidadeNotBetween(Integer value1, Integer value2) {
            addCriterion("id_funcionalidade not between", value1, value2, "idFuncionalidade");
            return (Criteria) this;
        }

        public Criteria andIdClienteIsNull() {
            addCriterion("id_cliente is null");
            return (Criteria) this;
        }

        public Criteria andIdClienteIsNotNull() {
            addCriterion("id_cliente is not null");
            return (Criteria) this;
        }

        public Criteria andIdClienteEqualTo(Integer value) {
            addCriterion("id_cliente =", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotEqualTo(Integer value) {
            addCriterion("id_cliente <>", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThan(Integer value) {
            addCriterion("id_cliente >", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cliente >=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThan(Integer value) {
            addCriterion("id_cliente <", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThanOrEqualTo(Integer value) {
            addCriterion("id_cliente <=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteIn(List<Integer> values) {
            addCriterion("id_cliente in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotIn(List<Integer> values) {
            addCriterion("id_cliente not in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteBetween(Integer value1, Integer value2) {
            addCriterion("id_cliente between", value1, value2, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cliente not between", value1, value2, "idCliente");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 22 17:51:58 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}