package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.ClienteEndereco;
import br.inf.orion.eSafe.model.ClienteEnderecoKey;
import br.inf.orion.eSafe.model.example.ClienteEnderecoExample;
import br.inf.orion.eSafe.service.provider.ClienteEnderecoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClienteEnderecoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=ClienteEnderecoSqlProvider.class, method="countByExample")
    long countByExample(ClienteEnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=ClienteEnderecoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClienteEnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_cliente_endereco",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(ClienteEnderecoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_cliente_endereco (id_cliente, id_sequencia, ",
        "tp_endereco, ds_logradouro, ",
        "ds_cidade, ds_estado, ",
        "nr_cep, ds_complemento, ",
        "ds_bairro)",
        "values (#{idCliente,jdbcType=INTEGER}, #{idSequencia,jdbcType=INTEGER}, ",
        "#{tpEndereco,jdbcType=INTEGER}, #{dsLogradouro,jdbcType=VARCHAR}, ",
        "#{dsCidade,jdbcType=VARCHAR}, #{dsEstado,jdbcType=CHAR}, ",
        "#{nrCep,jdbcType=CHAR}, #{dsComplemento,jdbcType=VARCHAR}, ",
        "#{dsBairro,jdbcType=VARCHAR})"
    })
    int insert(ClienteEndereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=ClienteEnderecoSqlProvider.class, method="insertSelective")
    int insertSelective(ClienteEndereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=ClienteEnderecoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_sequencia", property="idSequencia", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tp_endereco", property="tpEndereco", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_logradouro", property="dsLogradouro", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_cidade", property="dsCidade", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_estado", property="dsEstado", jdbcType=JdbcType.CHAR),
        @Result(column="nr_cep", property="nrCep", jdbcType=JdbcType.CHAR),
        @Result(column="ds_complemento", property="dsComplemento", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_bairro", property="dsBairro", jdbcType=JdbcType.VARCHAR)
    })
    List<ClienteEndereco> selectByExample(ClienteEnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Select({
        "select",
        "id_cliente, id_sequencia, tp_endereco, ds_logradouro, ds_cidade, ds_estado, ",
        "nr_cep, ds_complemento, ds_bairro",
        "from public.tb_cliente_endereco",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_sequencia", property="idSequencia", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tp_endereco", property="tpEndereco", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_logradouro", property="dsLogradouro", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_cidade", property="dsCidade", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_estado", property="dsEstado", jdbcType=JdbcType.CHAR),
        @Result(column="nr_cep", property="nrCep", jdbcType=JdbcType.CHAR),
        @Result(column="ds_complemento", property="dsComplemento", jdbcType=JdbcType.VARCHAR),
        @Result(column="ds_bairro", property="dsBairro", jdbcType=JdbcType.VARCHAR)
    })
    ClienteEndereco selectByPrimaryKey(ClienteEnderecoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteEnderecoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ClienteEndereco record, @Param("example") ClienteEnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteEnderecoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ClienteEndereco record, @Param("example") ClienteEnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteEnderecoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ClienteEndereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Update({
        "update public.tb_cliente_endereco",
        "set tp_endereco = #{tpEndereco,jdbcType=INTEGER},",
          "ds_logradouro = #{dsLogradouro,jdbcType=VARCHAR},",
          "ds_cidade = #{dsCidade,jdbcType=VARCHAR},",
          "ds_estado = #{dsEstado,jdbcType=CHAR},",
          "nr_cep = #{nrCep,jdbcType=CHAR},",
          "ds_complemento = #{dsComplemento,jdbcType=VARCHAR},",
          "ds_bairro = #{dsBairro,jdbcType=VARCHAR}",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ClienteEndereco record);
}