package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.ClienteContato;
import br.inf.orion.eSafe.model.ClienteContatoKey;
import br.inf.orion.eSafe.model.example.ClienteContatoExample;
import br.inf.orion.eSafe.service.provider.ClienteContatoSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClienteContatoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=ClienteContatoSqlProvider.class, method="countByExample")
    long countByExample(ClienteContatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=ClienteContatoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClienteContatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_cliente_contato",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(ClienteContatoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_cliente_contato (id_cliente, id_sequencia, ",
        "tp_contato, ds_contato, ",
        "tx_observacao)",
        "values (#{idCliente,jdbcType=INTEGER}, #{idSequencia,jdbcType=INTEGER}, ",
        "#{tpContato,jdbcType=INTEGER}, #{dsContato,jdbcType=VARCHAR}, ",
        "#{txObservacao,jdbcType=VARCHAR})"
    })
    int insert(ClienteContato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=ClienteContatoSqlProvider.class, method="insertSelective")
    int insertSelective(ClienteContato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=ClienteContatoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_sequencia", property="idSequencia", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tp_contato", property="tpContato", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_contato", property="dsContato", jdbcType=JdbcType.VARCHAR),
        @Result(column="tx_observacao", property="txObservacao", jdbcType=JdbcType.VARCHAR)
    })
    List<ClienteContato> selectByExample(ClienteContatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Select({
        "select",
        "id_cliente, id_sequencia, tp_contato, ds_contato, tx_observacao",
        "from public.tb_cliente_contato",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_sequencia", property="idSequencia", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="tp_contato", property="tpContato", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_contato", property="dsContato", jdbcType=JdbcType.VARCHAR),
        @Result(column="tx_observacao", property="txObservacao", jdbcType=JdbcType.VARCHAR)
    })
    ClienteContato selectByPrimaryKey(ClienteContatoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteContatoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ClienteContato record, @Param("example") ClienteContatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteContatoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ClienteContato record, @Param("example") ClienteContatoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=ClienteContatoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ClienteContato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_contato
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Update({
        "update public.tb_cliente_contato",
        "set tp_contato = #{tpContato,jdbcType=INTEGER},",
          "ds_contato = #{dsContato,jdbcType=VARCHAR},",
          "tx_observacao = #{txObservacao,jdbcType=VARCHAR}",
        "where id_cliente = #{idCliente,jdbcType=INTEGER}",
          "and id_sequencia = #{idSequencia,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ClienteContato record);
}