package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.FuncionalidadeClienteKey;
import br.inf.orion.eSafe.model.example.FuncionalidadeClienteExample;
import br.inf.orion.eSafe.service.provider.FuncionalidadeClienteSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FuncionalidadeClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=FuncionalidadeClienteSqlProvider.class, method="countByExample")
    long countByExample(FuncionalidadeClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=FuncionalidadeClienteSqlProvider.class, method="deleteByExample")
    int deleteByExample(FuncionalidadeClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_funcionalidade_cliente",
        "where id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}",
          "and id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(FuncionalidadeClienteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_funcionalidade_cliente (id_funcionalidade, id_cliente)",
        "values (#{idFuncionalidade,jdbcType=INTEGER}, #{idCliente,jdbcType=INTEGER})"
    })
    int insert(FuncionalidadeClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=FuncionalidadeClienteSqlProvider.class, method="insertSelective")
    int insertSelective(FuncionalidadeClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=FuncionalidadeClienteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_funcionalidade", property="idFuncionalidade", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<FuncionalidadeClienteKey> selectByExample(FuncionalidadeClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=FuncionalidadeClienteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FuncionalidadeClienteKey record, @Param("example") FuncionalidadeClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=FuncionalidadeClienteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FuncionalidadeClienteKey record, @Param("example") FuncionalidadeClienteExample example);
}