package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.FuncionalidadePerfilKey;
import br.inf.orion.eSafe.model.example.FuncionalidadePerfilExample;
import br.inf.orion.eSafe.service.provider.FuncionalidadePerfilSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FuncionalidadePerfilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=FuncionalidadePerfilSqlProvider.class, method="countByExample")
    long countByExample(FuncionalidadePerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=FuncionalidadePerfilSqlProvider.class, method="deleteByExample")
    int deleteByExample(FuncionalidadePerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_funcionalidade_perfil",
        "where id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}",
          "and id_perfil = #{idPerfil,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(FuncionalidadePerfilKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_funcionalidade_perfil (id_funcionalidade, id_perfil)",
        "values (#{idFuncionalidade,jdbcType=INTEGER}, #{idPerfil,jdbcType=INTEGER})"
    })
    int insert(FuncionalidadePerfilKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=FuncionalidadePerfilSqlProvider.class, method="insertSelective")
    int insertSelective(FuncionalidadePerfilKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=FuncionalidadePerfilSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_funcionalidade", property="idFuncionalidade", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_perfil", property="idPerfil", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<FuncionalidadePerfilKey> selectByExample(FuncionalidadePerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=FuncionalidadePerfilSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FuncionalidadePerfilKey record, @Param("example") FuncionalidadePerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_funcionalidade_perfil
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=FuncionalidadePerfilSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FuncionalidadePerfilKey record, @Param("example") FuncionalidadePerfilExample example);
}