package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.Funcionalidade;
import br.inf.orion.eSafe.model.example.FuncionalidadeExample;
import br.inf.orion.eSafe.service.provider.FuncionalidadeSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FuncionalidadeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = FuncionalidadeSqlProvider.class, method = "countByExample")
	long countByExample(FuncionalidadeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@DeleteProvider(type = FuncionalidadeSqlProvider.class, method = "deleteByExample")
	int deleteByExample(FuncionalidadeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Delete({ "delete from public.tb_funcionalidade",
			"where id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idFuncionalidade);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Insert({ "insert into public.tb_funcionalidade (ds_funcionalidade, ds_programa, ",
			"id_funcionalidade_anterior, id_sequencia, ", "id_sistema, ic_ativo, ", "ds_path, ds_icone)",
			"values (#{dsFuncionalidade,jdbcType=VARCHAR}, #{dsPrograma,jdbcType=VARCHAR}, ",
			"#{idFuncionalidadeAnterior,jdbcType=INTEGER}, #{idSequencia,jdbcType=INTEGER}, ",
			"#{idSistema,jdbcType=INTEGER}, #{icAtivo,jdbcType=BIT}, ",
			"#{dsPath,jdbcType=VARCHAR}, #{dsIcone,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT currval('tb_funcionalidade_id_funcionalidade_seq')", keyProperty = "idFuncionalidade", before = false, resultType = Integer.class)
	int insert(Funcionalidade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@InsertProvider(type = FuncionalidadeSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT currval('tb_funcionalidade_id_funcionalidade_seq')", keyProperty = "idFuncionalidade", before = false, resultType = Integer.class)
	int insertSelective(Funcionalidade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = FuncionalidadeSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id_funcionalidade", property = "idFuncionalidade", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_funcionalidade", property = "dsFuncionalidade", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_programa", property = "dsPrograma", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_funcionalidade_anterior", property = "idFuncionalidadeAnterior", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_sequencia", property = "idSequencia", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_sistema", property = "idSistema", jdbcType = JdbcType.INTEGER),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT),
			@Result(column = "ds_path", property = "dsPath", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_icone", property = "dsIcone", jdbcType = JdbcType.VARCHAR) })
	List<Funcionalidade> selectByExample(FuncionalidadeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Select({ "select", "id_funcionalidade, ds_funcionalidade, ds_programa, id_funcionalidade_anterior, ",
			"id_sequencia, id_sistema, ic_ativo, ds_path, ds_icone", "from public.tb_funcionalidade",
			"where id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id_funcionalidade", property = "idFuncionalidade", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_funcionalidade", property = "dsFuncionalidade", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_programa", property = "dsPrograma", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_funcionalidade_anterior", property = "idFuncionalidadeAnterior", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_sequencia", property = "idSequencia", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_sistema", property = "idSistema", jdbcType = JdbcType.INTEGER),
			@Result(column = "ic_ativo", property = "icAtivo", jdbcType = JdbcType.BIT),
			@Result(column = "ds_path", property = "dsPath", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ds_icone", property = "dsIcone", jdbcType = JdbcType.VARCHAR) })
	Funcionalidade selectByPrimaryKey(Integer idFuncionalidade);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = FuncionalidadeSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Funcionalidade record,
			@Param("example") FuncionalidadeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = FuncionalidadeSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Funcionalidade record, @Param("example") FuncionalidadeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = FuncionalidadeSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Funcionalidade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Update({ "update public.tb_funcionalidade", "set ds_funcionalidade = #{dsFuncionalidade,jdbcType=VARCHAR},",
			"ds_programa = #{dsPrograma,jdbcType=VARCHAR},",
			"id_funcionalidade_anterior = #{idFuncionalidadeAnterior,jdbcType=INTEGER},",
			"id_sequencia = #{idSequencia,jdbcType=INTEGER},", "id_sistema = #{idSistema,jdbcType=INTEGER},",
			"ic_ativo = #{icAtivo,jdbcType=BIT},", "ds_path = #{dsPath,jdbcType=VARCHAR},",
			"ds_icone = #{dsIcone,jdbcType=VARCHAR}",
			"where id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Funcionalidade record);
}