package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.Perfil;
import br.inf.orion.eSafe.model.example.PerfilExample;
import br.inf.orion.eSafe.service.provider.PerfilSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PerfilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @SelectProvider(type=PerfilSqlProvider.class, method="countByExample")
    long countByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @DeleteProvider(type=PerfilSqlProvider.class, method="deleteByExample")
    int deleteByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @Delete({
        "delete from public.tb_perfil",
        "where id_perfil = #{idPerfil,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idPerfil);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @Insert({
        "insert into public.tb_perfil (ds_perfil, tp_perfil, ",
        "ic_nivel, ds_rules)",
        "values (#{dsPerfil,jdbcType=VARCHAR}, #{tpPerfil,jdbcType=INTEGER}, ",
        "#{icNivel,jdbcType=INTEGER}, #{dsRules,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT currval('tb_perfil_id_perfil_seq')", keyProperty="idPerfil", before=false, resultType=Integer.class)
    int insert(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @InsertProvider(type=PerfilSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT currval('tb_perfil_id_perfil_seq')", keyProperty="idPerfil", before=false, resultType=Integer.class)
    int insertSelective(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @SelectProvider(type=PerfilSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_perfil", property="idPerfil", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_perfil", property="dsPerfil", jdbcType=JdbcType.VARCHAR),
        @Result(column="tp_perfil", property="tpPerfil", jdbcType=JdbcType.INTEGER),
        @Result(column="ic_nivel", property="icNivel", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_rules", property="dsRules", jdbcType=JdbcType.VARCHAR)
    })
    List<Perfil> selectByExample(PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @Select({
        "select",
        "id_perfil, ds_perfil, tp_perfil, ic_nivel, ds_rules",
        "from public.tb_perfil",
        "where id_perfil = #{idPerfil,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id_perfil", property="idPerfil", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ds_perfil", property="dsPerfil", jdbcType=JdbcType.VARCHAR),
        @Result(column="tp_perfil", property="tpPerfil", jdbcType=JdbcType.INTEGER),
        @Result(column="ic_nivel", property="icNivel", jdbcType=JdbcType.INTEGER),
        @Result(column="ds_rules", property="dsRules", jdbcType=JdbcType.VARCHAR)
    })
    Perfil selectByPrimaryKey(Integer idPerfil);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @UpdateProvider(type=PerfilSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Perfil record, @Param("example") PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @UpdateProvider(type=PerfilSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Perfil record, @Param("example") PerfilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @UpdateProvider(type=PerfilSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Perfil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    @Update({
        "update public.tb_perfil",
        "set ds_perfil = #{dsPerfil,jdbcType=VARCHAR},",
          "tp_perfil = #{tpPerfil,jdbcType=INTEGER},",
          "ic_nivel = #{icNivel,jdbcType=INTEGER},",
          "ds_rules = #{dsRules,jdbcType=VARCHAR}",
        "where id_perfil = #{idPerfil,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Perfil record);
}