package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.SistemaClienteKey;
import br.inf.orion.eSafe.model.example.SistemaClienteExample;
import br.inf.orion.eSafe.service.provider.SistemaClienteSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SistemaClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=SistemaClienteSqlProvider.class, method="countByExample")
    long countByExample(SistemaClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=SistemaClienteSqlProvider.class, method="deleteByExample")
    int deleteByExample(SistemaClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_sistema_cliente",
        "where id_sistema = #{idSistema,jdbcType=INTEGER}",
          "and id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(SistemaClienteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_sistema_cliente (id_sistema, id_cliente)",
        "values (#{idSistema,jdbcType=INTEGER}, #{idCliente,jdbcType=INTEGER})"
    })
    int insert(SistemaClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=SistemaClienteSqlProvider.class, method="insertSelective")
    int insertSelective(SistemaClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=SistemaClienteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_sistema", property="idSistema", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<SistemaClienteKey> selectByExample(SistemaClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=SistemaClienteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SistemaClienteKey record, @Param("example") SistemaClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_sistema_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=SistemaClienteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SistemaClienteKey record, @Param("example") SistemaClienteExample example);
}