package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.Sistema;
import br.inf.orion.eSafe.model.example.SistemaExample;
import br.inf.orion.eSafe.service.provider.SistemaSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SistemaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = SistemaSqlProvider.class, method = "countByExample")
	long countByExample(SistemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@DeleteProvider(type = SistemaSqlProvider.class, method = "deleteByExample")
	int deleteByExample(SistemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Delete({ "delete from public.tb_sistema", "where id_sistema = #{idSistema,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idSistema);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Insert({ "insert into public.tb_sistema (ds_sistema)", "values (#{dsSistema,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT currval('tb_sistema_id_sistema_seq')", keyProperty = "idSistema", before = false, resultType = Integer.class)
	int insert(Sistema record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@InsertProvider(type = SistemaSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT currval('tb_sistema_id_sistema_seq')", keyProperty = "idSistema", before = false, resultType = Integer.class)
	int insertSelective(Sistema record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = SistemaSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_sistema", property = "idSistema", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_sistema", property = "dsSistema", jdbcType = JdbcType.VARCHAR) })
	List<Sistema> selectByExample(SistemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Select({ "select", "id_sistema, ds_sistema", "from public.tb_sistema",
			"where id_sistema = #{idSistema,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_sistema", property = "idSistema", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ds_sistema", property = "dsSistema", jdbcType = JdbcType.VARCHAR) })
	Sistema selectByPrimaryKey(Integer idSistema);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = SistemaSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Sistema record, @Param("example") SistemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = SistemaSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Sistema record, @Param("example") SistemaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = SistemaSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Sistema record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sistema
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Update({ "update public.tb_sistema", "set ds_sistema = #{dsSistema,jdbcType=VARCHAR}",
			"where id_sistema = #{idSistema,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Sistema record);
}