package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.Terminal;
import br.inf.orion.eSafe.model.example.TerminalExample;
import br.inf.orion.eSafe.service.provider.TerminalSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TerminalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = TerminalSqlProvider.class, method = "countByExample")
	long countByExample(TerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@DeleteProvider(type = TerminalSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Delete({ "delete from public.tb_terminal", "where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer idTerminal);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Insert({ "insert into public.tb_terminal (id_cliente, nr_terminal)",
			"values (#{idCliente,jdbcType=INTEGER}, #{nrTerminal,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT currval('tb_terminal_id_terminal_seq')", keyProperty = "idTerminal", before = false, resultType = Integer.class)
	int insert(Terminal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@InsertProvider(type = TerminalSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT currval('tb_terminal_id_terminal_seq')", keyProperty = "idTerminal", before = false, resultType = Integer.class)
	int insertSelective(Terminal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@SelectProvider(type = TerminalSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_cliente", property = "idCliente", jdbcType = JdbcType.INTEGER),
			@Result(column = "nr_terminal", property = "nrTerminal", jdbcType = JdbcType.VARCHAR) })
	List<Terminal> selectByExample(TerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Select({ "select", "id_terminal, id_cliente, nr_terminal", "from public.tb_terminal",
			"where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id_terminal", property = "idTerminal", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_cliente", property = "idCliente", jdbcType = JdbcType.INTEGER),
			@Result(column = "nr_terminal", property = "nrTerminal", jdbcType = JdbcType.VARCHAR) })
	Terminal selectByPrimaryKey(Integer idTerminal);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = TerminalSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Terminal record, @Param("example") TerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = TerminalSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Terminal record, @Param("example") TerminalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@UpdateProvider(type = TerminalSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Terminal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_terminal
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	@Update({ "update public.tb_terminal", "set id_cliente = #{idCliente,jdbcType=INTEGER},",
			"nr_terminal = #{nrTerminal,jdbcType=VARCHAR}", "where id_terminal = #{idTerminal,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Terminal record);
}