package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.UsuarioTerminalKey;
import br.inf.orion.eSafe.model.example.UsuarioTerminalExample;
import br.inf.orion.eSafe.service.provider.UsuarioTerminalSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsuarioTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=UsuarioTerminalSqlProvider.class, method="countByExample")
    long countByExample(UsuarioTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=UsuarioTerminalSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsuarioTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_usuario_terminal",
        "where id_terminal = #{idTerminal,jdbcType=INTEGER}",
          "and id_usuario = #{idUsuario,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UsuarioTerminalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_usuario_terminal (id_terminal, id_usuario)",
        "values (#{idTerminal,jdbcType=INTEGER}, #{idUsuario,jdbcType=INTEGER})"
    })
    int insert(UsuarioTerminalKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=UsuarioTerminalSqlProvider.class, method="insertSelective")
    int insertSelective(UsuarioTerminalKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=UsuarioTerminalSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_terminal", property="idTerminal", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_usuario", property="idUsuario", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<UsuarioTerminalKey> selectByExample(UsuarioTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=UsuarioTerminalSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UsuarioTerminalKey record, @Param("example") UsuarioTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_terminal
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=UsuarioTerminalSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UsuarioTerminalKey record, @Param("example") UsuarioTerminalExample example);
}