package br.inf.orion.eSafe.model.mapper;

import br.inf.orion.eSafe.model.UsuarioClienteKey;
import br.inf.orion.eSafe.model.example.UsuarioClienteExample;
import br.inf.orion.eSafe.service.provider.UsuarioClienteSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UsuarioClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=UsuarioClienteSqlProvider.class, method="countByExample")
    long countByExample(UsuarioClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @DeleteProvider(type=UsuarioClienteSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsuarioClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Delete({
        "delete from public.tb_usuario_cliente",
        "where id_usuario = #{idUsuario,jdbcType=INTEGER}",
          "and id_cliente = #{idCliente,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UsuarioClienteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @Insert({
        "insert into public.tb_usuario_cliente (id_usuario, id_cliente)",
        "values (#{idUsuario,jdbcType=INTEGER}, #{idCliente,jdbcType=INTEGER})"
    })
    int insert(UsuarioClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @InsertProvider(type=UsuarioClienteSqlProvider.class, method="insertSelective")
    int insertSelective(UsuarioClienteKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @SelectProvider(type=UsuarioClienteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id_usuario", property="idUsuario", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id_cliente", property="idCliente", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<UsuarioClienteKey> selectByExample(UsuarioClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=UsuarioClienteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UsuarioClienteKey record, @Param("example") UsuarioClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_usuario_cliente
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    @UpdateProvider(type=UsuarioClienteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UsuarioClienteKey record, @Param("example") UsuarioClienteExample example);
}