package br.inf.orion.eSafe.service.dao.client;

import br.inf.orion.eSafe.model.client.Fornecedor;
import br.inf.orion.eSafe.model.client.example.TbFornecedorExample;
import br.inf.orion.eSafe.model.client.example.TbFornecedorExample.Criteria;
import br.inf.orion.eSafe.model.client.example.TbFornecedorExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbFornecedorSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String countByExample(TbFornecedorExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("public.tb_fornecedor");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String deleteByExample(TbFornecedorExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("public.tb_fornecedor");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String insertSelective(Fornecedor record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("public.tb_fornecedor");
		if (record.getIdFornecedor() != null) {
			sql.VALUES("id_fornecedor", "#{idFornecedor,jdbcType=INTEGER}");
		}
		if (record.getDsFornecedor() != null) {
			sql.VALUES("ds_fornecedor", "#{dsFornecedor,jdbcType=VARCHAR}");
		}
		if (record.getDsCnpj() != null) {
			sql.VALUES("ds_cnpj", "#{dsCnpj,jdbcType=VARCHAR}");
		}
		if (record.getIcAtivo() != null) {
			sql.VALUES("ic_ativo", "#{icAtivo,jdbcType=BIT}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String selectByExample(TbFornecedorExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id_fornecedor");
		} else {
			sql.SELECT("id_fornecedor");
		}
		sql.SELECT("ds_fornecedor");
		sql.SELECT("ds_cnpj");
		sql.SELECT("ic_ativo");
		sql.FROM("public.tb_fornecedor");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Fornecedor record = (Fornecedor) parameter.get("record");
		TbFornecedorExample example = (TbFornecedorExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("public.tb_fornecedor");
		if (record.getIdFornecedor() != null) {
			sql.SET("id_fornecedor = #{record.idFornecedor,jdbcType=INTEGER}");
		}
		if (record.getDsFornecedor() != null) {
			sql.SET("ds_fornecedor = #{record.dsFornecedor,jdbcType=VARCHAR}");
		}
		if (record.getDsCnpj() != null) {
			sql.SET("ds_cnpj = #{record.dsCnpj,jdbcType=VARCHAR}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_fornecedor");
		sql.SET("id_fornecedor = #{record.idFornecedor,jdbcType=INTEGER}");
		sql.SET("ds_fornecedor = #{record.dsFornecedor,jdbcType=VARCHAR}");
		sql.SET("ds_cnpj = #{record.dsCnpj,jdbcType=VARCHAR}");
		sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		TbFornecedorExample example = (TbFornecedorExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String updateByPrimaryKeySelective(Fornecedor record) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_fornecedor");
		if (record.getDsFornecedor() != null) {
			sql.SET("ds_fornecedor = #{dsFornecedor,jdbcType=VARCHAR}");
		}
		if (record.getDsCnpj() != null) {
			sql.SET("ds_cnpj = #{dsCnpj,jdbcType=VARCHAR}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{icAtivo,jdbcType=BIT}");
		}
		sql.WHERE("id_fornecedor = #{idFornecedor,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected void applyWhere(SQL sql, TbFornecedorExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}