package br.inf.orion.eSafe.service.provider;

import br.inf.orion.eSafe.model.ClienteEndereco;
import br.inf.orion.eSafe.model.example.ClienteEnderecoExample;
import br.inf.orion.eSafe.model.example.ClienteEnderecoExample.Criteria;
import br.inf.orion.eSafe.model.example.ClienteEnderecoExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ClienteEnderecoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String countByExample(ClienteEnderecoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("public.tb_cliente_endereco");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String deleteByExample(ClienteEnderecoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("public.tb_cliente_endereco");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String insertSelective(ClienteEndereco record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("public.tb_cliente_endereco");
        
        if (record.getIdCliente() != null) {
            sql.VALUES("id_cliente", "#{idCliente,jdbcType=INTEGER}");
        }
        
        if (record.getIdSequencia() != null) {
            sql.VALUES("id_sequencia", "#{idSequencia,jdbcType=INTEGER}");
        }
        
        if (record.getTpEndereco() != null) {
            sql.VALUES("tp_endereco", "#{tpEndereco,jdbcType=INTEGER}");
        }
        
        if (record.getDsLogradouro() != null) {
            sql.VALUES("ds_logradouro", "#{dsLogradouro,jdbcType=VARCHAR}");
        }
        
        if (record.getDsCidade() != null) {
            sql.VALUES("ds_cidade", "#{dsCidade,jdbcType=VARCHAR}");
        }
        
        if (record.getDsEstado() != null) {
            sql.VALUES("ds_estado", "#{dsEstado,jdbcType=CHAR}");
        }
        
        if (record.getNrCep() != null) {
            sql.VALUES("nr_cep", "#{nrCep,jdbcType=CHAR}");
        }
        
        if (record.getDsComplemento() != null) {
            sql.VALUES("ds_complemento", "#{dsComplemento,jdbcType=VARCHAR}");
        }
        
        if (record.getDsBairro() != null) {
            sql.VALUES("ds_bairro", "#{dsBairro,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String selectByExample(ClienteEnderecoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id_cliente");
        } else {
            sql.SELECT("id_cliente");
        }
        sql.SELECT("id_sequencia");
        sql.SELECT("tp_endereco");
        sql.SELECT("ds_logradouro");
        sql.SELECT("ds_cidade");
        sql.SELECT("ds_estado");
        sql.SELECT("nr_cep");
        sql.SELECT("ds_complemento");
        sql.SELECT("ds_bairro");
        sql.FROM("public.tb_cliente_endereco");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ClienteEndereco record = (ClienteEndereco) parameter.get("record");
        ClienteEnderecoExample example = (ClienteEnderecoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("public.tb_cliente_endereco");
        
        if (record.getIdCliente() != null) {
            sql.SET("id_cliente = #{record.idCliente,jdbcType=INTEGER}");
        }
        
        if (record.getIdSequencia() != null) {
            sql.SET("id_sequencia = #{record.idSequencia,jdbcType=INTEGER}");
        }
        
        if (record.getTpEndereco() != null) {
            sql.SET("tp_endereco = #{record.tpEndereco,jdbcType=INTEGER}");
        }
        
        if (record.getDsLogradouro() != null) {
            sql.SET("ds_logradouro = #{record.dsLogradouro,jdbcType=VARCHAR}");
        }
        
        if (record.getDsCidade() != null) {
            sql.SET("ds_cidade = #{record.dsCidade,jdbcType=VARCHAR}");
        }
        
        if (record.getDsEstado() != null) {
            sql.SET("ds_estado = #{record.dsEstado,jdbcType=CHAR}");
        }
        
        if (record.getNrCep() != null) {
            sql.SET("nr_cep = #{record.nrCep,jdbcType=CHAR}");
        }
        
        if (record.getDsComplemento() != null) {
            sql.SET("ds_complemento = #{record.dsComplemento,jdbcType=VARCHAR}");
        }
        
        if (record.getDsBairro() != null) {
            sql.SET("ds_bairro = #{record.dsBairro,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_cliente_endereco");
        
        sql.SET("id_cliente = #{record.idCliente,jdbcType=INTEGER}");
        sql.SET("id_sequencia = #{record.idSequencia,jdbcType=INTEGER}");
        sql.SET("tp_endereco = #{record.tpEndereco,jdbcType=INTEGER}");
        sql.SET("ds_logradouro = #{record.dsLogradouro,jdbcType=VARCHAR}");
        sql.SET("ds_cidade = #{record.dsCidade,jdbcType=VARCHAR}");
        sql.SET("ds_estado = #{record.dsEstado,jdbcType=CHAR}");
        sql.SET("nr_cep = #{record.nrCep,jdbcType=CHAR}");
        sql.SET("ds_complemento = #{record.dsComplemento,jdbcType=VARCHAR}");
        sql.SET("ds_bairro = #{record.dsBairro,jdbcType=VARCHAR}");
        
        ClienteEnderecoExample example = (ClienteEnderecoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByPrimaryKeySelective(ClienteEndereco record) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_cliente_endereco");
        
        if (record.getTpEndereco() != null) {
            sql.SET("tp_endereco = #{tpEndereco,jdbcType=INTEGER}");
        }
        
        if (record.getDsLogradouro() != null) {
            sql.SET("ds_logradouro = #{dsLogradouro,jdbcType=VARCHAR}");
        }
        
        if (record.getDsCidade() != null) {
            sql.SET("ds_cidade = #{dsCidade,jdbcType=VARCHAR}");
        }
        
        if (record.getDsEstado() != null) {
            sql.SET("ds_estado = #{dsEstado,jdbcType=CHAR}");
        }
        
        if (record.getNrCep() != null) {
            sql.SET("nr_cep = #{nrCep,jdbcType=CHAR}");
        }
        
        if (record.getDsComplemento() != null) {
            sql.SET("ds_complemento = #{dsComplemento,jdbcType=VARCHAR}");
        }
        
        if (record.getDsBairro() != null) {
            sql.SET("ds_bairro = #{dsBairro,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id_cliente = #{idCliente,jdbcType=INTEGER}");
        sql.WHERE("id_sequencia = #{idSequencia,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_cliente_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected void applyWhere(SQL sql, ClienteEnderecoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}