package br.inf.orion.eSafe.service.provider;

import br.inf.orion.eSafe.model.Funcionalidade;
import br.inf.orion.eSafe.model.example.FuncionalidadeExample;
import br.inf.orion.eSafe.model.example.FuncionalidadeExample.Criteria;
import br.inf.orion.eSafe.model.example.FuncionalidadeExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class FuncionalidadeSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String countByExample(FuncionalidadeExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("public.tb_funcionalidade");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String deleteByExample(FuncionalidadeExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("public.tb_funcionalidade");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String insertSelective(Funcionalidade record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("public.tb_funcionalidade");
		if (record.getDsFuncionalidade() != null) {
			sql.VALUES("ds_funcionalidade", "#{dsFuncionalidade,jdbcType=VARCHAR}");
		}
		if (record.getDsPrograma() != null) {
			sql.VALUES("ds_programa", "#{dsPrograma,jdbcType=VARCHAR}");
		}
		if (record.getIdFuncionalidadeAnterior() != null) {
			sql.VALUES("id_funcionalidade_anterior", "#{idFuncionalidadeAnterior,jdbcType=INTEGER}");
		}
		if (record.getIdSequencia() != null) {
			sql.VALUES("id_sequencia", "#{idSequencia,jdbcType=INTEGER}");
		}
		if (record.getIdSistema() != null) {
			sql.VALUES("id_sistema", "#{idSistema,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.VALUES("ic_ativo", "#{icAtivo,jdbcType=BIT}");
		}
		if (record.getDsPath() != null) {
			sql.VALUES("ds_path", "#{dsPath,jdbcType=VARCHAR}");
		}
		if (record.getDsIcone() != null) {
			sql.VALUES("ds_icone", "#{dsIcone,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String selectByExample(FuncionalidadeExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id_funcionalidade");
		} else {
			sql.SELECT("id_funcionalidade");
		}
		sql.SELECT("ds_funcionalidade");
		sql.SELECT("ds_programa");
		sql.SELECT("id_funcionalidade_anterior");
		sql.SELECT("id_sequencia");
		sql.SELECT("id_sistema");
		sql.SELECT("ic_ativo");
		sql.SELECT("ds_path");
		sql.SELECT("ds_icone");
		sql.FROM("public.tb_funcionalidade");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Funcionalidade record = (Funcionalidade) parameter.get("record");
		FuncionalidadeExample example = (FuncionalidadeExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("public.tb_funcionalidade");
		if (record.getIdFuncionalidade() != null) {
			sql.SET("id_funcionalidade = #{record.idFuncionalidade,jdbcType=INTEGER}");
		}
		if (record.getDsFuncionalidade() != null) {
			sql.SET("ds_funcionalidade = #{record.dsFuncionalidade,jdbcType=VARCHAR}");
		}
		if (record.getDsPrograma() != null) {
			sql.SET("ds_programa = #{record.dsPrograma,jdbcType=VARCHAR}");
		}
		if (record.getIdFuncionalidadeAnterior() != null) {
			sql.SET("id_funcionalidade_anterior = #{record.idFuncionalidadeAnterior,jdbcType=INTEGER}");
		}
		if (record.getIdSequencia() != null) {
			sql.SET("id_sequencia = #{record.idSequencia,jdbcType=INTEGER}");
		}
		if (record.getIdSistema() != null) {
			sql.SET("id_sistema = #{record.idSistema,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		}
		if (record.getDsPath() != null) {
			sql.SET("ds_path = #{record.dsPath,jdbcType=VARCHAR}");
		}
		if (record.getDsIcone() != null) {
			sql.SET("ds_icone = #{record.dsIcone,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_funcionalidade");
		sql.SET("id_funcionalidade = #{record.idFuncionalidade,jdbcType=INTEGER}");
		sql.SET("ds_funcionalidade = #{record.dsFuncionalidade,jdbcType=VARCHAR}");
		sql.SET("ds_programa = #{record.dsPrograma,jdbcType=VARCHAR}");
		sql.SET("id_funcionalidade_anterior = #{record.idFuncionalidadeAnterior,jdbcType=INTEGER}");
		sql.SET("id_sequencia = #{record.idSequencia,jdbcType=INTEGER}");
		sql.SET("id_sistema = #{record.idSistema,jdbcType=INTEGER}");
		sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		sql.SET("ds_path = #{record.dsPath,jdbcType=VARCHAR}");
		sql.SET("ds_icone = #{record.dsIcone,jdbcType=VARCHAR}");
		FuncionalidadeExample example = (FuncionalidadeExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByPrimaryKeySelective(Funcionalidade record) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_funcionalidade");
		if (record.getDsFuncionalidade() != null) {
			sql.SET("ds_funcionalidade = #{dsFuncionalidade,jdbcType=VARCHAR}");
		}
		if (record.getDsPrograma() != null) {
			sql.SET("ds_programa = #{dsPrograma,jdbcType=VARCHAR}");
		}
		if (record.getIdFuncionalidadeAnterior() != null) {
			sql.SET("id_funcionalidade_anterior = #{idFuncionalidadeAnterior,jdbcType=INTEGER}");
		}
		if (record.getIdSequencia() != null) {
			sql.SET("id_sequencia = #{idSequencia,jdbcType=INTEGER}");
		}
		if (record.getIdSistema() != null) {
			sql.SET("id_sistema = #{idSistema,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{icAtivo,jdbcType=BIT}");
		}
		if (record.getDsPath() != null) {
			sql.SET("ds_path = #{dsPath,jdbcType=VARCHAR}");
		}
		if (record.getDsIcone() != null) {
			sql.SET("ds_icone = #{dsIcone,jdbcType=VARCHAR}");
		}
		sql.WHERE("id_funcionalidade = #{idFuncionalidade,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_funcionalidade
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected void applyWhere(SQL sql, FuncionalidadeExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}