package br.inf.orion.eSafe.service.provider;

import br.inf.orion.eSafe.model.Perfil;
import br.inf.orion.eSafe.model.example.PerfilExample;
import br.inf.orion.eSafe.model.example.PerfilExample.Criteria;
import br.inf.orion.eSafe.model.example.PerfilExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PerfilSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String countByExample(PerfilExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("public.tb_perfil");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String deleteByExample(PerfilExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("public.tb_perfil");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String insertSelective(Perfil record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("public.tb_perfil");
        
        if (record.getDsPerfil() != null) {
            sql.VALUES("ds_perfil", "#{dsPerfil,jdbcType=VARCHAR}");
        }
        
        if (record.getTpPerfil() != null) {
            sql.VALUES("tp_perfil", "#{tpPerfil,jdbcType=INTEGER}");
        }
        
        if (record.getIcNivel() != null) {
            sql.VALUES("ic_nivel", "#{icNivel,jdbcType=INTEGER}");
        }
        
        if (record.getDsRules() != null) {
            sql.VALUES("ds_rules", "#{dsRules,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String selectByExample(PerfilExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id_perfil");
        } else {
            sql.SELECT("id_perfil");
        }
        sql.SELECT("ds_perfil");
        sql.SELECT("tp_perfil");
        sql.SELECT("ic_nivel");
        sql.SELECT("ds_rules");
        sql.FROM("public.tb_perfil");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Perfil record = (Perfil) parameter.get("record");
        PerfilExample example = (PerfilExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("public.tb_perfil");
        
        if (record.getIdPerfil() != null) {
            sql.SET("id_perfil = #{record.idPerfil,jdbcType=INTEGER}");
        }
        
        if (record.getDsPerfil() != null) {
            sql.SET("ds_perfil = #{record.dsPerfil,jdbcType=VARCHAR}");
        }
        
        if (record.getTpPerfil() != null) {
            sql.SET("tp_perfil = #{record.tpPerfil,jdbcType=INTEGER}");
        }
        
        if (record.getIcNivel() != null) {
            sql.SET("ic_nivel = #{record.icNivel,jdbcType=INTEGER}");
        }
        
        if (record.getDsRules() != null) {
            sql.SET("ds_rules = #{record.dsRules,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_perfil");
        
        sql.SET("id_perfil = #{record.idPerfil,jdbcType=INTEGER}");
        sql.SET("ds_perfil = #{record.dsPerfil,jdbcType=VARCHAR}");
        sql.SET("tp_perfil = #{record.tpPerfil,jdbcType=INTEGER}");
        sql.SET("ic_nivel = #{record.icNivel,jdbcType=INTEGER}");
        sql.SET("ds_rules = #{record.dsRules,jdbcType=VARCHAR}");
        
        PerfilExample example = (PerfilExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    public String updateByPrimaryKeySelective(Perfil record) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_perfil");
        
        if (record.getDsPerfil() != null) {
            sql.SET("ds_perfil = #{dsPerfil,jdbcType=VARCHAR}");
        }
        
        if (record.getTpPerfil() != null) {
            sql.SET("tp_perfil = #{tpPerfil,jdbcType=INTEGER}");
        }
        
        if (record.getIcNivel() != null) {
            sql.SET("ic_nivel = #{icNivel,jdbcType=INTEGER}");
        }
        
        if (record.getDsRules() != null) {
            sql.SET("ds_rules = #{dsRules,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id_perfil = #{idPerfil,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_perfil
     *
     * @mbg.generated Tue Jan 31 14:31:43 BRST 2017
     */
    protected void applyWhere(SQL sql, PerfilExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}