package br.inf.orion.eSafe.service.provider;

import br.inf.orion.eSafe.model.TipoEndereco;
import br.inf.orion.eSafe.model.example.TipoEnderecoExample;
import br.inf.orion.eSafe.model.example.TipoEnderecoExample.Criteria;
import br.inf.orion.eSafe.model.example.TipoEnderecoExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TipoEnderecoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String countByExample(TipoEnderecoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("public.tb_tipo_endereco");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String deleteByExample(TipoEnderecoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("public.tb_tipo_endereco");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String insertSelective(TipoEndereco record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("public.tb_tipo_endereco");
        
        if (record.getTpEndereco() != null) {
            sql.VALUES("tp_endereco", "#{tpEndereco,jdbcType=INTEGER}");
        }
        
        if (record.getDsTipoEndereco() != null) {
            sql.VALUES("ds_tipo_endereco", "#{dsTipoEndereco,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String selectByExample(TipoEnderecoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("tp_endereco");
        } else {
            sql.SELECT("tp_endereco");
        }
        sql.SELECT("ds_tipo_endereco");
        sql.FROM("public.tb_tipo_endereco");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TipoEndereco record = (TipoEndereco) parameter.get("record");
        TipoEnderecoExample example = (TipoEnderecoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("public.tb_tipo_endereco");
        
        if (record.getTpEndereco() != null) {
            sql.SET("tp_endereco = #{record.tpEndereco,jdbcType=INTEGER}");
        }
        
        if (record.getDsTipoEndereco() != null) {
            sql.SET("ds_tipo_endereco = #{record.dsTipoEndereco,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_tipo_endereco");
        
        sql.SET("tp_endereco = #{record.tpEndereco,jdbcType=INTEGER}");
        sql.SET("ds_tipo_endereco = #{record.dsTipoEndereco,jdbcType=VARCHAR}");
        
        TipoEnderecoExample example = (TipoEnderecoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    public String updateByPrimaryKeySelective(TipoEndereco record) {
        SQL sql = new SQL();
        sql.UPDATE("public.tb_tipo_endereco");
        
        if (record.getDsTipoEndereco() != null) {
            sql.SET("ds_tipo_endereco = #{dsTipoEndereco,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("tp_endereco = #{tpEndereco,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_tipo_endereco
     *
     * @mbg.generated Thu Dec 22 17:51:58 BRST 2016
     */
    protected void applyWhere(SQL sql, TipoEnderecoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}