package br.inf.orion.eSafe.service.provider;

import br.inf.orion.eSafe.model.Usuario;
import br.inf.orion.eSafe.model.example.UsuarioExample;
import br.inf.orion.eSafe.model.example.UsuarioExample.Criteria;
import br.inf.orion.eSafe.model.example.UsuarioExample.Criterion;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UsuarioSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String countByExample(UsuarioExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("public.tb_usuario");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String deleteByExample(UsuarioExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("public.tb_usuario");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String insertSelective(Usuario record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("public.tb_usuario");
		if (record.getDsLogin() != null) {
			sql.VALUES("ds_login", "#{dsLogin,jdbcType=VARCHAR}");
		}
		if (record.getDsEmail() != null) {
			sql.VALUES("ds_email", "#{dsEmail,jdbcType=VARCHAR}");
		}
		if (record.getDsSenha() != null) {
			sql.VALUES("ds_senha", "#{dsSenha,jdbcType=VARCHAR}");
		}
		if (record.getDsNomeUsuario() != null) {
			sql.VALUES("ds_nome_usuario", "#{dsNomeUsuario,jdbcType=VARCHAR}");
		}
		if (record.getDtCriacao() != null) {
			sql.VALUES("dt_criacao", "#{dtCriacao,jdbcType=TIMESTAMP}");
		}
		if (record.getDtAlteracao() != null) {
			sql.VALUES("dt_alteracao", "#{dtAlteracao,jdbcType=TIMESTAMP}");
		}
		if (record.getDsToken() != null) {
			sql.VALUES("ds_token", "#{dsToken,jdbcType=VARCHAR}");
		}
		if (record.getDtGeraToken() != null) {
			sql.VALUES("dt_gera_token", "#{dtGeraToken,jdbcType=TIMESTAMP}");
		}
		if (record.getIdPerfil() != null) {
			sql.VALUES("id_perfil", "#{idPerfil,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.VALUES("ic_ativo", "#{icAtivo,jdbcType=BIT}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String selectByExample(UsuarioExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id_usuario");
		} else {
			sql.SELECT("id_usuario");
		}
		sql.SELECT("ds_login");
		sql.SELECT("ds_email");
		sql.SELECT("ds_senha");
		sql.SELECT("ds_nome_usuario");
		sql.SELECT("dt_criacao");
		sql.SELECT("dt_alteracao");
		sql.SELECT("ds_token");
		sql.SELECT("dt_gera_token");
		sql.SELECT("id_perfil");
		sql.SELECT("ic_ativo");
		sql.FROM("public.tb_usuario");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Usuario record = (Usuario) parameter.get("record");
		UsuarioExample example = (UsuarioExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("public.tb_usuario");
		if (record.getIdUsuario() != null) {
			sql.SET("id_usuario = #{record.idUsuario,jdbcType=INTEGER}");
		}
		if (record.getDsLogin() != null) {
			sql.SET("ds_login = #{record.dsLogin,jdbcType=VARCHAR}");
		}
		if (record.getDsEmail() != null) {
			sql.SET("ds_email = #{record.dsEmail,jdbcType=VARCHAR}");
		}
		if (record.getDsSenha() != null) {
			sql.SET("ds_senha = #{record.dsSenha,jdbcType=VARCHAR}");
		}
		if (record.getDsNomeUsuario() != null) {
			sql.SET("ds_nome_usuario = #{record.dsNomeUsuario,jdbcType=VARCHAR}");
		}
		if (record.getDtCriacao() != null) {
			sql.SET("dt_criacao = #{record.dtCriacao,jdbcType=TIMESTAMP}");
		}
		if (record.getDtAlteracao() != null) {
			sql.SET("dt_alteracao = #{record.dtAlteracao,jdbcType=TIMESTAMP}");
		}
		if (record.getDsToken() != null) {
			sql.SET("ds_token = #{record.dsToken,jdbcType=VARCHAR}");
		}
		if (record.getDtGeraToken() != null) {
			sql.SET("dt_gera_token = #{record.dtGeraToken,jdbcType=TIMESTAMP}");
		}
		if (record.getIdPerfil() != null) {
			sql.SET("id_perfil = #{record.idPerfil,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_usuario");
		sql.SET("id_usuario = #{record.idUsuario,jdbcType=INTEGER}");
		sql.SET("ds_login = #{record.dsLogin,jdbcType=VARCHAR}");
		sql.SET("ds_email = #{record.dsEmail,jdbcType=VARCHAR}");
		sql.SET("ds_senha = #{record.dsSenha,jdbcType=VARCHAR}");
		sql.SET("ds_nome_usuario = #{record.dsNomeUsuario,jdbcType=VARCHAR}");
		sql.SET("dt_criacao = #{record.dtCriacao,jdbcType=TIMESTAMP}");
		sql.SET("dt_alteracao = #{record.dtAlteracao,jdbcType=TIMESTAMP}");
		sql.SET("ds_token = #{record.dsToken,jdbcType=VARCHAR}");
		sql.SET("dt_gera_token = #{record.dtGeraToken,jdbcType=TIMESTAMP}");
		sql.SET("id_perfil = #{record.idPerfil,jdbcType=INTEGER}");
		sql.SET("ic_ativo = #{record.icAtivo,jdbcType=BIT}");
		UsuarioExample example = (UsuarioExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	public String updateByPrimaryKeySelective(Usuario record) {
		SQL sql = new SQL();
		sql.UPDATE("public.tb_usuario");
		if (record.getDsLogin() != null) {
			sql.SET("ds_login = #{dsLogin,jdbcType=VARCHAR}");
		}
		if (record.getDsEmail() != null) {
			sql.SET("ds_email = #{dsEmail,jdbcType=VARCHAR}");
		}
		if (record.getDsSenha() != null) {
			sql.SET("ds_senha = #{dsSenha,jdbcType=VARCHAR}");
		}
		if (record.getDsNomeUsuario() != null) {
			sql.SET("ds_nome_usuario = #{dsNomeUsuario,jdbcType=VARCHAR}");
		}
		if (record.getDtCriacao() != null) {
			sql.SET("dt_criacao = #{dtCriacao,jdbcType=TIMESTAMP}");
		}
		if (record.getDtAlteracao() != null) {
			sql.SET("dt_alteracao = #{dtAlteracao,jdbcType=TIMESTAMP}");
		}
		if (record.getDsToken() != null) {
			sql.SET("ds_token = #{dsToken,jdbcType=VARCHAR}");
		}
		if (record.getDtGeraToken() != null) {
			sql.SET("dt_gera_token = #{dtGeraToken,jdbcType=TIMESTAMP}");
		}
		if (record.getIdPerfil() != null) {
			sql.SET("id_perfil = #{idPerfil,jdbcType=INTEGER}");
		}
		if (record.getIcAtivo() != null) {
			sql.SET("ic_ativo = #{icAtivo,jdbcType=BIT}");
		}
		sql.WHERE("id_usuario = #{idUsuario,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_usuario
	 * @mbg.generated  Thu Dec 22 23:43:27 BRST 2016
	 */
	protected void applyWhere(SQL sql, UsuarioExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}