package br.inf.orion.eSafe.client.model.example;

import java.util.ArrayList;
import java.util.List;

public class EnderecoEstabelecimentoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public EnderecoEstabelecimentoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdEstabelecimentoIsNull() {
			addCriterion("id_estabelecimento is null");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoIsNotNull() {
			addCriterion("id_estabelecimento is not null");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoEqualTo(Integer value) {
			addCriterion("id_estabelecimento =", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoNotEqualTo(Integer value) {
			addCriterion("id_estabelecimento <>", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoGreaterThan(Integer value) {
			addCriterion("id_estabelecimento >", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_estabelecimento >=", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoLessThan(Integer value) {
			addCriterion("id_estabelecimento <", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoLessThanOrEqualTo(Integer value) {
			addCriterion("id_estabelecimento <=", value, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoIn(List<Integer> values) {
			addCriterion("id_estabelecimento in", values, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoNotIn(List<Integer> values) {
			addCriterion("id_estabelecimento not in", values, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoBetween(Integer value1, Integer value2) {
			addCriterion("id_estabelecimento between", value1, value2, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEstabelecimentoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_estabelecimento not between", value1, value2, "idEstabelecimento");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoIsNull() {
			addCriterion("id_endereco is null");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoIsNotNull() {
			addCriterion("id_endereco is not null");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoEqualTo(Integer value) {
			addCriterion("id_endereco =", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoNotEqualTo(Integer value) {
			addCriterion("id_endereco <>", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoGreaterThan(Integer value) {
			addCriterion("id_endereco >", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_endereco >=", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoLessThan(Integer value) {
			addCriterion("id_endereco <", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoLessThanOrEqualTo(Integer value) {
			addCriterion("id_endereco <=", value, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoIn(List<Integer> values) {
			addCriterion("id_endereco in", values, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoNotIn(List<Integer> values) {
			addCriterion("id_endereco not in", values, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoBetween(Integer value1, Integer value2) {
			addCriterion("id_endereco between", value1, value2, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andIdEnderecoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_endereco not between", value1, value2, "idEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoIsNull() {
			addCriterion("tp_endereco is null");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoIsNotNull() {
			addCriterion("tp_endereco is not null");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoEqualTo(Integer value) {
			addCriterion("tp_endereco =", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoNotEqualTo(Integer value) {
			addCriterion("tp_endereco <>", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoGreaterThan(Integer value) {
			addCriterion("tp_endereco >", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoGreaterThanOrEqualTo(Integer value) {
			addCriterion("tp_endereco >=", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoLessThan(Integer value) {
			addCriterion("tp_endereco <", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoLessThanOrEqualTo(Integer value) {
			addCriterion("tp_endereco <=", value, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoIn(List<Integer> values) {
			addCriterion("tp_endereco in", values, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoNotIn(List<Integer> values) {
			addCriterion("tp_endereco not in", values, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoBetween(Integer value1, Integer value2) {
			addCriterion("tp_endereco between", value1, value2, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andTpEnderecoNotBetween(Integer value1, Integer value2) {
			addCriterion("tp_endereco not between", value1, value2, "tpEndereco");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroIsNull() {
			addCriterion("ds_logradouro is null");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroIsNotNull() {
			addCriterion("ds_logradouro is not null");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroEqualTo(String value) {
			addCriterion("ds_logradouro =", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroNotEqualTo(String value) {
			addCriterion("ds_logradouro <>", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroGreaterThan(String value) {
			addCriterion("ds_logradouro >", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroGreaterThanOrEqualTo(String value) {
			addCriterion("ds_logradouro >=", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroLessThan(String value) {
			addCriterion("ds_logradouro <", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroLessThanOrEqualTo(String value) {
			addCriterion("ds_logradouro <=", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroLike(String value) {
			addCriterion("ds_logradouro like", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroNotLike(String value) {
			addCriterion("ds_logradouro not like", value, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroIn(List<String> values) {
			addCriterion("ds_logradouro in", values, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroNotIn(List<String> values) {
			addCriterion("ds_logradouro not in", values, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroBetween(String value1, String value2) {
			addCriterion("ds_logradouro between", value1, value2, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsLogradouroNotBetween(String value1, String value2) {
			addCriterion("ds_logradouro not between", value1, value2, "dsLogradouro");
			return (Criteria) this;
		}

		public Criteria andDsComplementoIsNull() {
			addCriterion("ds_complemento is null");
			return (Criteria) this;
		}

		public Criteria andDsComplementoIsNotNull() {
			addCriterion("ds_complemento is not null");
			return (Criteria) this;
		}

		public Criteria andDsComplementoEqualTo(String value) {
			addCriterion("ds_complemento =", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoNotEqualTo(String value) {
			addCriterion("ds_complemento <>", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoGreaterThan(String value) {
			addCriterion("ds_complemento >", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoGreaterThanOrEqualTo(String value) {
			addCriterion("ds_complemento >=", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoLessThan(String value) {
			addCriterion("ds_complemento <", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoLessThanOrEqualTo(String value) {
			addCriterion("ds_complemento <=", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoLike(String value) {
			addCriterion("ds_complemento like", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoNotLike(String value) {
			addCriterion("ds_complemento not like", value, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoIn(List<String> values) {
			addCriterion("ds_complemento in", values, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoNotIn(List<String> values) {
			addCriterion("ds_complemento not in", values, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoBetween(String value1, String value2) {
			addCriterion("ds_complemento between", value1, value2, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsComplementoNotBetween(String value1, String value2) {
			addCriterion("ds_complemento not between", value1, value2, "dsComplemento");
			return (Criteria) this;
		}

		public Criteria andDsBairroIsNull() {
			addCriterion("ds_bairro is null");
			return (Criteria) this;
		}

		public Criteria andDsBairroIsNotNull() {
			addCriterion("ds_bairro is not null");
			return (Criteria) this;
		}

		public Criteria andDsBairroEqualTo(String value) {
			addCriterion("ds_bairro =", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroNotEqualTo(String value) {
			addCriterion("ds_bairro <>", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroGreaterThan(String value) {
			addCriterion("ds_bairro >", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroGreaterThanOrEqualTo(String value) {
			addCriterion("ds_bairro >=", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroLessThan(String value) {
			addCriterion("ds_bairro <", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroLessThanOrEqualTo(String value) {
			addCriterion("ds_bairro <=", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroLike(String value) {
			addCriterion("ds_bairro like", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroNotLike(String value) {
			addCriterion("ds_bairro not like", value, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroIn(List<String> values) {
			addCriterion("ds_bairro in", values, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroNotIn(List<String> values) {
			addCriterion("ds_bairro not in", values, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroBetween(String value1, String value2) {
			addCriterion("ds_bairro between", value1, value2, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsBairroNotBetween(String value1, String value2) {
			addCriterion("ds_bairro not between", value1, value2, "dsBairro");
			return (Criteria) this;
		}

		public Criteria andDsCidadeIsNull() {
			addCriterion("ds_cidade is null");
			return (Criteria) this;
		}

		public Criteria andDsCidadeIsNotNull() {
			addCriterion("ds_cidade is not null");
			return (Criteria) this;
		}

		public Criteria andDsCidadeEqualTo(String value) {
			addCriterion("ds_cidade =", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeNotEqualTo(String value) {
			addCriterion("ds_cidade <>", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeGreaterThan(String value) {
			addCriterion("ds_cidade >", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeGreaterThanOrEqualTo(String value) {
			addCriterion("ds_cidade >=", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeLessThan(String value) {
			addCriterion("ds_cidade <", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeLessThanOrEqualTo(String value) {
			addCriterion("ds_cidade <=", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeLike(String value) {
			addCriterion("ds_cidade like", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeNotLike(String value) {
			addCriterion("ds_cidade not like", value, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeIn(List<String> values) {
			addCriterion("ds_cidade in", values, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeNotIn(List<String> values) {
			addCriterion("ds_cidade not in", values, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeBetween(String value1, String value2) {
			addCriterion("ds_cidade between", value1, value2, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsCidadeNotBetween(String value1, String value2) {
			addCriterion("ds_cidade not between", value1, value2, "dsCidade");
			return (Criteria) this;
		}

		public Criteria andDsEstadoIsNull() {
			addCriterion("ds_estado is null");
			return (Criteria) this;
		}

		public Criteria andDsEstadoIsNotNull() {
			addCriterion("ds_estado is not null");
			return (Criteria) this;
		}

		public Criteria andDsEstadoEqualTo(String value) {
			addCriterion("ds_estado =", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoNotEqualTo(String value) {
			addCriterion("ds_estado <>", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoGreaterThan(String value) {
			addCriterion("ds_estado >", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoGreaterThanOrEqualTo(String value) {
			addCriterion("ds_estado >=", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoLessThan(String value) {
			addCriterion("ds_estado <", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoLessThanOrEqualTo(String value) {
			addCriterion("ds_estado <=", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoLike(String value) {
			addCriterion("ds_estado like", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoNotLike(String value) {
			addCriterion("ds_estado not like", value, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoIn(List<String> values) {
			addCriterion("ds_estado in", values, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoNotIn(List<String> values) {
			addCriterion("ds_estado not in", values, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoBetween(String value1, String value2) {
			addCriterion("ds_estado between", value1, value2, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsEstadoNotBetween(String value1, String value2) {
			addCriterion("ds_estado not between", value1, value2, "dsEstado");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalIsNull() {
			addCriterion("ds_codigo_postal is null");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalIsNotNull() {
			addCriterion("ds_codigo_postal is not null");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalEqualTo(String value) {
			addCriterion("ds_codigo_postal =", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalNotEqualTo(String value) {
			addCriterion("ds_codigo_postal <>", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalGreaterThan(String value) {
			addCriterion("ds_codigo_postal >", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalGreaterThanOrEqualTo(String value) {
			addCriterion("ds_codigo_postal >=", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalLessThan(String value) {
			addCriterion("ds_codigo_postal <", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalLessThanOrEqualTo(String value) {
			addCriterion("ds_codigo_postal <=", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalLike(String value) {
			addCriterion("ds_codigo_postal like", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalNotLike(String value) {
			addCriterion("ds_codigo_postal not like", value, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalIn(List<String> values) {
			addCriterion("ds_codigo_postal in", values, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalNotIn(List<String> values) {
			addCriterion("ds_codigo_postal not in", values, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalBetween(String value1, String value2) {
			addCriterion("ds_codigo_postal between", value1, value2, "dsCodigoPostal");
			return (Criteria) this;
		}

		public Criteria andDsCodigoPostalNotBetween(String value1, String value2) {
			addCriterion("ds_codigo_postal not between", value1, value2, "dsCodigoPostal");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_endereco_estabelecimento
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_endereco_estabelecimento
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 02 12:03:10 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}