package br.inf.orion.eSafe.client.model.example;

import java.util.ArrayList;
import java.util.List;

public class FornecedorExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public FornecedorExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdFornecedorIsNull() {
			addCriterion("id_fornecedor is null");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorIsNotNull() {
			addCriterion("id_fornecedor is not null");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorEqualTo(Integer value) {
			addCriterion("id_fornecedor =", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorNotEqualTo(Integer value) {
			addCriterion("id_fornecedor <>", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorGreaterThan(Integer value) {
			addCriterion("id_fornecedor >", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_fornecedor >=", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorLessThan(Integer value) {
			addCriterion("id_fornecedor <", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorLessThanOrEqualTo(Integer value) {
			addCriterion("id_fornecedor <=", value, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorIn(List<Integer> values) {
			addCriterion("id_fornecedor in", values, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorNotIn(List<Integer> values) {
			addCriterion("id_fornecedor not in", values, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorBetween(Integer value1, Integer value2) {
			addCriterion("id_fornecedor between", value1, value2, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andIdFornecedorNotBetween(Integer value1, Integer value2) {
			addCriterion("id_fornecedor not between", value1, value2, "idFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorIsNull() {
			addCriterion("ds_fornecedor is null");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorIsNotNull() {
			addCriterion("ds_fornecedor is not null");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorEqualTo(String value) {
			addCriterion("ds_fornecedor =", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorNotEqualTo(String value) {
			addCriterion("ds_fornecedor <>", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorGreaterThan(String value) {
			addCriterion("ds_fornecedor >", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorGreaterThanOrEqualTo(String value) {
			addCriterion("ds_fornecedor >=", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorLessThan(String value) {
			addCriterion("ds_fornecedor <", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorLessThanOrEqualTo(String value) {
			addCriterion("ds_fornecedor <=", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorLike(String value) {
			addCriterion("ds_fornecedor like", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorNotLike(String value) {
			addCriterion("ds_fornecedor not like", value, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorIn(List<String> values) {
			addCriterion("ds_fornecedor in", values, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorNotIn(List<String> values) {
			addCriterion("ds_fornecedor not in", values, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorBetween(String value1, String value2) {
			addCriterion("ds_fornecedor between", value1, value2, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsFornecedorNotBetween(String value1, String value2) {
			addCriterion("ds_fornecedor not between", value1, value2, "dsFornecedor");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIsNull() {
			addCriterion("ds_cnpj is null");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIsNotNull() {
			addCriterion("ds_cnpj is not null");
			return (Criteria) this;
		}

		public Criteria andDsCnpjEqualTo(String value) {
			addCriterion("ds_cnpj =", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotEqualTo(String value) {
			addCriterion("ds_cnpj <>", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjGreaterThan(String value) {
			addCriterion("ds_cnpj >", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjGreaterThanOrEqualTo(String value) {
			addCriterion("ds_cnpj >=", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLessThan(String value) {
			addCriterion("ds_cnpj <", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLessThanOrEqualTo(String value) {
			addCriterion("ds_cnpj <=", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjLike(String value) {
			addCriterion("ds_cnpj like", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotLike(String value) {
			addCriterion("ds_cnpj not like", value, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjIn(List<String> values) {
			addCriterion("ds_cnpj in", values, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotIn(List<String> values) {
			addCriterion("ds_cnpj not in", values, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjBetween(String value1, String value2) {
			addCriterion("ds_cnpj between", value1, value2, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andDsCnpjNotBetween(String value1, String value2) {
			addCriterion("ds_cnpj not between", value1, value2, "dsCnpj");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNull() {
			addCriterion("ic_ativo is null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIsNotNull() {
			addCriterion("ic_ativo is not null");
			return (Criteria) this;
		}

		public Criteria andIcAtivoEqualTo(Boolean value) {
			addCriterion("ic_ativo =", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotEqualTo(Boolean value) {
			addCriterion("ic_ativo <>", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThan(Boolean value) {
			addCriterion("ic_ativo >", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo >=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThan(Boolean value) {
			addCriterion("ic_ativo <", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoLessThanOrEqualTo(Boolean value) {
			addCriterion("ic_ativo <=", value, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoIn(List<Boolean> values) {
			addCriterion("ic_ativo in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotIn(List<Boolean> values) {
			addCriterion("ic_ativo not in", values, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo between", value1, value2, "icAtivo");
			return (Criteria) this;
		}

		public Criteria andIcAtivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ic_ativo not between", value1, value2, "icAtivo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_fornecedor
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_fornecedor
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 02 12:03:09 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}