package br.inf.orion.eSafe.client.model.example;

import java.util.ArrayList;
import java.util.List;

public class SensorExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public SensorExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdDispositivoIsNull() {
			addCriterion("id_dispositivo is null");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoIsNotNull() {
			addCriterion("id_dispositivo is not null");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoEqualTo(Integer value) {
			addCriterion("id_dispositivo =", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotEqualTo(Integer value) {
			addCriterion("id_dispositivo <>", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoGreaterThan(Integer value) {
			addCriterion("id_dispositivo >", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_dispositivo >=", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoLessThan(Integer value) {
			addCriterion("id_dispositivo <", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoLessThanOrEqualTo(Integer value) {
			addCriterion("id_dispositivo <=", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoIn(List<Integer> values) {
			addCriterion("id_dispositivo in", values, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotIn(List<Integer> values) {
			addCriterion("id_dispositivo not in", values, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoBetween(Integer value1, Integer value2) {
			addCriterion("id_dispositivo between", value1, value2, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_dispositivo not between", value1, value2, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdSensorIsNull() {
			addCriterion("id_sensor is null");
			return (Criteria) this;
		}

		public Criteria andIdSensorIsNotNull() {
			addCriterion("id_sensor is not null");
			return (Criteria) this;
		}

		public Criteria andIdSensorEqualTo(Integer value) {
			addCriterion("id_sensor =", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorNotEqualTo(Integer value) {
			addCriterion("id_sensor <>", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorGreaterThan(Integer value) {
			addCriterion("id_sensor >", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sensor >=", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorLessThan(Integer value) {
			addCriterion("id_sensor <", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorLessThanOrEqualTo(Integer value) {
			addCriterion("id_sensor <=", value, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorIn(List<Integer> values) {
			addCriterion("id_sensor in", values, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorNotIn(List<Integer> values) {
			addCriterion("id_sensor not in", values, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorBetween(Integer value1, Integer value2) {
			addCriterion("id_sensor between", value1, value2, "idSensor");
			return (Criteria) this;
		}

		public Criteria andIdSensorNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sensor not between", value1, value2, "idSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorIsNull() {
			addCriterion("ds_sensor is null");
			return (Criteria) this;
		}

		public Criteria andDsSensorIsNotNull() {
			addCriterion("ds_sensor is not null");
			return (Criteria) this;
		}

		public Criteria andDsSensorEqualTo(String value) {
			addCriterion("ds_sensor =", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorNotEqualTo(String value) {
			addCriterion("ds_sensor <>", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorGreaterThan(String value) {
			addCriterion("ds_sensor >", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorGreaterThanOrEqualTo(String value) {
			addCriterion("ds_sensor >=", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorLessThan(String value) {
			addCriterion("ds_sensor <", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorLessThanOrEqualTo(String value) {
			addCriterion("ds_sensor <=", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorLike(String value) {
			addCriterion("ds_sensor like", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorNotLike(String value) {
			addCriterion("ds_sensor not like", value, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorIn(List<String> values) {
			addCriterion("ds_sensor in", values, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorNotIn(List<String> values) {
			addCriterion("ds_sensor not in", values, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorBetween(String value1, String value2) {
			addCriterion("ds_sensor between", value1, value2, "dsSensor");
			return (Criteria) this;
		}

		public Criteria andDsSensorNotBetween(String value1, String value2) {
			addCriterion("ds_sensor not between", value1, value2, "dsSensor");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_sensor
	 * @mbg.generated  Tue Jan 03 16:28:52 BRST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_sensor
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 03 16:27:15 BRST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}