package br.inf.orion.eSafe.client.model.example;

import java.util.ArrayList;
import java.util.List;

public class StatusDispositivoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public StatusDispositivoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdDispositivoIsNull() {
			addCriterion("id_dispositivo is null");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoIsNotNull() {
			addCriterion("id_dispositivo is not null");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoEqualTo(Integer value) {
			addCriterion("id_dispositivo =", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotEqualTo(Integer value) {
			addCriterion("id_dispositivo <>", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoGreaterThan(Integer value) {
			addCriterion("id_dispositivo >", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_dispositivo >=", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoLessThan(Integer value) {
			addCriterion("id_dispositivo <", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoLessThanOrEqualTo(Integer value) {
			addCriterion("id_dispositivo <=", value, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoIn(List<Integer> values) {
			addCriterion("id_dispositivo in", values, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotIn(List<Integer> values) {
			addCriterion("id_dispositivo not in", values, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoBetween(Integer value1, Integer value2) {
			addCriterion("id_dispositivo between", value1, value2, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andIdDispositivoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_dispositivo not between", value1, value2, "idDispositivo");
			return (Criteria) this;
		}

		public Criteria andCdStatusIsNull() {
			addCriterion("cd_status is null");
			return (Criteria) this;
		}

		public Criteria andCdStatusIsNotNull() {
			addCriterion("cd_status is not null");
			return (Criteria) this;
		}

		public Criteria andCdStatusEqualTo(Integer value) {
			addCriterion("cd_status =", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusNotEqualTo(Integer value) {
			addCriterion("cd_status <>", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusGreaterThan(Integer value) {
			addCriterion("cd_status >", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("cd_status >=", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusLessThan(Integer value) {
			addCriterion("cd_status <", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusLessThanOrEqualTo(Integer value) {
			addCriterion("cd_status <=", value, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusIn(List<Integer> values) {
			addCriterion("cd_status in", values, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusNotIn(List<Integer> values) {
			addCriterion("cd_status not in", values, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusBetween(Integer value1, Integer value2) {
			addCriterion("cd_status between", value1, value2, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andCdStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("cd_status not between", value1, value2, "cdStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusIsNull() {
			addCriterion("ds_status is null");
			return (Criteria) this;
		}

		public Criteria andDsStatusIsNotNull() {
			addCriterion("ds_status is not null");
			return (Criteria) this;
		}

		public Criteria andDsStatusEqualTo(String value) {
			addCriterion("ds_status =", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusNotEqualTo(String value) {
			addCriterion("ds_status <>", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusGreaterThan(String value) {
			addCriterion("ds_status >", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ds_status >=", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusLessThan(String value) {
			addCriterion("ds_status <", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusLessThanOrEqualTo(String value) {
			addCriterion("ds_status <=", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusLike(String value) {
			addCriterion("ds_status like", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusNotLike(String value) {
			addCriterion("ds_status not like", value, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusIn(List<String> values) {
			addCriterion("ds_status in", values, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusNotIn(List<String> values) {
			addCriterion("ds_status not in", values, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusBetween(String value1, String value2) {
			addCriterion("ds_status between", value1, value2, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andDsStatusNotBetween(String value1, String value2) {
			addCriterion("ds_status not between", value1, value2, "dsStatus");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeIsNull() {
			addCriterion("id_severidade is null");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeIsNotNull() {
			addCriterion("id_severidade is not null");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeEqualTo(Integer value) {
			addCriterion("id_severidade =", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeNotEqualTo(Integer value) {
			addCriterion("id_severidade <>", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeGreaterThan(Integer value) {
			addCriterion("id_severidade >", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_severidade >=", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeLessThan(Integer value) {
			addCriterion("id_severidade <", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeLessThanOrEqualTo(Integer value) {
			addCriterion("id_severidade <=", value, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeIn(List<Integer> values) {
			addCriterion("id_severidade in", values, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeNotIn(List<Integer> values) {
			addCriterion("id_severidade not in", values, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeBetween(Integer value1, Integer value2) {
			addCriterion("id_severidade between", value1, value2, "idSeveridade");
			return (Criteria) this;
		}

		public Criteria andIdSeveridadeNotBetween(Integer value1, Integer value2) {
			addCriterion("id_severidade not between", value1, value2, "idSeveridade");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_status_dispositivo
	 * @mbg.generated  Fri Dec 02 12:03:10 BRST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_status_dispositivo
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 02 12:03:10 BRST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}